//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using System.Data.SqlClient;
using System.Data;
using System.Data.Common;
using System.Reflection;

using DY.Data;
using DY.Entity;
using DY.Config;

namespace DY.Data.SqlServer
{
    public partial class DataProvider : IDataProvider
    {
        /// <summary>
        /// 插入Cms
        /// </summary>
        /// <param name="adinfo"></param>
        public int InsertCmsInfo(CmsInfo entity)
        {
            Type entityType = entity.GetType();
            PropertyInfo[] propertyInfos = entityType.GetProperties();
            StringBuilder sb = new StringBuilder("INSERT INTO {0}cms ("), sbParamer = new StringBuilder(" (");
            List<DbParameter> paramerList = new List<DbParameter>(); //参数集合
            foreach (PropertyInfo property in propertyInfos)
            {
                object oval = property.GetValue(entity, null);
                oval = oval == null ? DBNull.Value : oval;

                if (oval.GetType() != typeof(System.DBNull))
                {
                    if (property.Name != "article_id")
                    {
                        sb.Append(property.Name);
                        sb.Append(",");

                        sbParamer.Append("@" + property.Name);
                        sbParamer.Append(",");

                        paramerList.Add(DbHelper.MakeInParam("@" + property.Name, DbHelper.MakeDbType(oval), 0, oval));
                    }
                }
            }

            //截取掉最后一个多于的参数分隔','符号
            sb.Remove(sb.Length - 1, 1);
            sbParamer.Remove(sbParamer.Length - 1, 1);

            //拼接最终SQL
            sb.Append(") VALUES ");
            sb.Append(sbParamer.ToString() + ")");
            sb.Append(";SELECT SCOPE_IDENTITY()");

            string SQL = string.Format(sb.ToString(), BaseConfig.TablePrefix);
            //throw new Exception(SQL);
            return Convert.ToInt32(DbHelper.ExecuteScalar(CommandType.Text, SQL, paramerList.ToArray()));
        }
        /// <summary>
        /// 更新Cms
        /// </summary>
        /// <param name="deliveryinfo"></param>
        public void UpdateCmsInfo(CmsInfo entity)
        {
            Type entityType = entity.GetType();
            PropertyInfo[] propertyInfos = entityType.GetProperties();
            StringBuilder sb = new StringBuilder("UPDATE {0}cms SET ");
            List<DbParameter> paramerList = new List<DbParameter>(); //参数集合
            foreach (PropertyInfo property in propertyInfos)
            {
                object oval = property.GetValue(entity, null);
                oval = oval == null ? DBNull.Value : oval;

                if (oval.GetType() != typeof(System.DBNull))
                {
                    if (property.Name != "article_id")
                    {
                        sb.Append(property.Name + "=@" + property.Name);
                        sb.Append(",");
                    }

                    paramerList.Add(DbHelper.MakeInParam("@" + property.Name, DbHelper.MakeDbType(oval),0, oval));
                }
            }
            sb.Remove(sb.Length - 1, 1);
            sb.Append(" WHERE article_id=@article_id");

            string SQL = string.Format(sb.ToString(),BaseConfig.TablePrefix);

            DbHelper.ExecuteNonQuery(CommandType.Text, SQL, paramerList.ToArray());
        }
        /// <summary>
        /// 获取Cms信息
        /// </summary>
        /// <param name="ad_id"></param>
        /// <returns></returns>
        public DbDataReader GetCmsInfo(int article_id)
        {
            string SQL = string.Format("SELECT * FROM {0}cms WHERE [article_id]=@article_id", BaseConfig.TablePrefix);

            DbParameter[] parms = {
	            DbHelper.MakeInParam("@article_id", (DbType)SqlDbType.Int, 4, article_id)
            };

            return DbHelper.ExecuteReader(CommandType.Text, SQL, parms);
        }
        /// <summary>
        /// 获取Cms信息
        /// </summary>
        /// <param name="filter"></param>
        /// <returns></returns>
        public DbDataReader GetCmsInfo(string filter)
        {
            if (!string.IsNullOrEmpty(filter))
                filter = "and " + filter;

            string SQL = string.Format("SELECT * FROM {0}cms WHERE [article_id]>0 {1}", BaseConfig.TablePrefix, filter);

            return DbHelper.ExecuteReader(CommandType.Text, SQL);
        }
        /// <summary>
        /// 删除Cms信息（按主键删除）
        /// </summary>
        /// <param name="ad_id"></param>
        /// <returns></returns>
        public void DeleteCmsInfo(int article_id)
        {
            string SQL = string.Format("DELETE FROM {0}cms WHERE [article_id]=@article_id", BaseConfig.TablePrefix);

            DbParameter[] parms = {
	            DbHelper.MakeInParam("@article_id", (DbType)SqlDbType.Int, 4, article_id)
            };

            DbHelper.ExecuteNonQuery(CommandType.Text, SQL, parms);
        }
        /// <summary>
        /// 是否存在
        /// </summary>
        /// <param name="filter"></param>
        /// <returns></returns>
        public bool ExistsCms(string filter)
        {
            if (!string.IsNullOrEmpty(filter))
                filter = "and " + filter;

            string SQL = string.Format("SELECT COUNT(article_id) FROM {0}cms WHERE [article_id]>0 {1}", BaseConfig.TablePrefix, filter);

            return Convert.ToInt32(DbHelper.ExecuteScalarToStr(CommandType.Text, SQL)) > 0 ? true : false;
        }
        /// <summary>
        /// 获取Cms单个值
        /// </summary>
        /// <param name="Fields"></param>
        /// <param name="filter"></param>
        /// <returns></returns>
        public object GetCmsValue(string Fields, string filter)
        {
            if (!string.IsNullOrEmpty(filter))
                filter = "and " + filter;

            string SQL = string.Format("SELECT {2} FROM {0}cms WHERE [article_id]>0 {1}", BaseConfig.TablePrefix, filter,Fields);

            return DbHelper.ExecuteScalarToStr(CommandType.Text, SQL);
        }


        /// <summary>
        /// 移动资讯位置
        /// </summary>
        /// <param name="act"></param>
        /// <param name="article_id"></param>
        /// <returns></returns>
        public int MoveCmsPos(string act, int article_id)
        {
            int state = 0;
            System.Data.SqlClient.SqlConnection conn = new System.Data.SqlClient.SqlConnection(DbHelper.ConnectionString);
            conn.Open();

            using (System.Data.SqlClient.SqlTransaction trans = conn.BeginTransaction())
            {
                try
                {
                    DataRow curcat = DbHelper.ExecuteDataset(trans, CommandType.Text, string.Format("SELECT TOP 1 * FROM {0}cms WHERE article_id={1}", BaseConfig.TablePrefix, article_id)).Tables[0].Rows[0];

                    #region 向上移动
                    if (act == "up")
                    {
                        //更新其它分类位置
                        //DbHelper.ExecuteNonQuery(trans, CommandType.Text, string.Format("UPDATE {0}cms SET sort_order=sort_order+1 WHERE sort_order<{1} and cat_level={2} and parent_id={3}", BaseConfig.TablePrefix, Convert.ToInt32(curcat["sort_order"]), Convert.ToInt32(curcat["cat_level"]), Convert.ToInt32(curcat["parent_id"])));

                        //更新当前位置
                        DbHelper.ExecuteNonQuery(trans, CommandType.Text, string.Format("UPDATE {0}cms SET sort_order=sort_order+1 WHERE article_id={1}", BaseConfig.TablePrefix, article_id));
                    }
                    #endregion

                    #region 向下移动
                    else if (act == "down")
                    {
                        //更新当前位置
                        DbHelper.ExecuteNonQuery(trans, CommandType.Text, string.Format("UPDATE {0}cms SET sort_order=sort_order-1 WHERE article_id={1}", BaseConfig.TablePrefix, article_id));
                    }
                    #endregion

                    trans.Commit();
                }
                catch (Exception ex)
                {
                    trans.Rollback();
                    throw ex;
                }
                conn.Close();
            }

            return state;
        }
    }
}