//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DY.Entity {

    /// <summary>
    /// AdminAction实体
    /// </summary>
    [Serializable]
    public class AdminActionInfo {

        // Internal member variables
        
        private System.Int32? _action_id;
        private System.Int32? _parent_id;
        private System.String _action_code;
        private System.String _action_text;
        private System.Boolean? _isenable;
        private List<AdminActionInfo> _children;  
        /// <summary>
        /// Default constructor
        /// </summary>
        public AdminActionInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="action_id">AdminAction action_id</param>
        /// <param name="parent_id">AdminAction parent_id</param>
        /// <param name="action_code">AdminAction action_code</param>
        /// <param name="action_text">AdminAction action_text</param>
        /// <param name="isenable">AdminAction isenable</param>
        public AdminActionInfo(System.Int32 action_id,System.Int32 parent_id,System.String action_code,System.String action_text,System.Boolean isenable) {
            this._action_id = action_id;
            this._parent_id = parent_id;
            this._action_code = action_code;
            this._action_text = action_text;
            this._isenable = isenable;
            
        }
        /// <summary>
        /// 
        /// </summary>
        public List<AdminActionInfo> children
        {
            get { return _children; }
            set { _children = value; }
        }  
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? action_id {
            get { return _action_id; }
            set { _action_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? parent_id {
            get { return _parent_id; }
            set { _parent_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String action_code {
            get { return _action_code; }
            set { _action_code = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String action_text {
            get { return _action_text; }
            set { _action_text = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? isenable {
            get { return _isenable; }
            set { _isenable = value; }
        }
        
    }
}