//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// AdminUser实体
    /// </summary>
    [Serializable]
    public class AdminUserInfo {

        // Internal member variables
        
        private System.Int32? _user_id;
        private System.String _user_name;
        private System.String _email;
        private System.String _password;
        private System.DateTime? _add_time;
        private System.DateTime? _last_login;
        private System.String _last_ip;
        private System.String _action_list;
        private System.String _nav_list;
        private System.String _lang_type;
        private System.Int32? _agency_id;
        private System.String _todolist;

        /// <summary>
        /// Default constructor
        /// </summary>
        public AdminUserInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="user_id">AdminUser user_id</param>
        /// <param name="user_name">AdminUser user_name</param>
        /// <param name="email">AdminUser email</param>
        /// <param name="password">AdminUser password</param>
        /// <param name="add_time">AdminUser add_time</param>
        /// <param name="last_login">AdminUser last_login</param>
        /// <param name="last_ip">AdminUser last_ip</param>
        /// <param name="action_list">AdminUser action_list</param>
        /// <param name="nav_list">AdminUser nav_list</param>
        /// <param name="lang_type">AdminUser lang_type</param>
        /// <param name="agency_id">AdminUser agency_id</param>
        /// <param name="todolist">AdminUser todolist</param>
        public AdminUserInfo(System.Int32 user_id,System.String user_name,System.String email,System.String password,System.DateTime add_time,System.DateTime last_login,System.String last_ip,System.String action_list,System.String nav_list,System.String lang_type,System.Int32 agency_id,System.String todolist) {
            this._user_id = user_id;
            this._user_name = user_name;
            this._email = email;
            this._password = password;
            this._add_time = add_time;
            this._last_login = last_login;
            this._last_ip = last_ip;
            this._action_list = action_list;
            this._nav_list = nav_list;
            this._lang_type = lang_type;
            this._agency_id = agency_id;
            this._todolist = todolist;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? user_id {
            get { return _user_id; }
            set { _user_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String user_name {
            get { return _user_name; }
            set { _user_name = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String email {
            get { return _email; }
            set { _email = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String password {
            get { return _password; }
            set { _password = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? add_time {
            get { return _add_time; }
            set { _add_time = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? last_login {
            get { return _last_login; }
            set { _last_login = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String last_ip {
            get { return _last_ip; }
            set { _last_ip = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String action_list {
            get { return _action_list; }
            set { _action_list = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String nav_list {
            get { return _nav_list; }
            set { _nav_list = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String lang_type {
            get { return _lang_type; }
            set { _lang_type = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? agency_id {
            get { return _agency_id; }
            set { _agency_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String todolist {
            get { return _todolist; }
            set { _todolist = value; }
        }
        
    }
}