//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// AdPosition实体
    /// </summary>
    [Serializable]
    public class AdPositionInfo {

        // Internal member variables
        
        private System.Int32? _position_id;
        private System.String _position_name;
        private System.Int32? _ad_width;
        private System.Int32? _ad_height;
        private System.String _position_desc;
        private System.String _position_style;
        private System.String _position_url;
        private System.Int32? _position_type;
        private System.Boolean? _is_show_text;

        /// <summary>
        /// Default constructor
        /// </summary>
        public AdPositionInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="position_id">AdPosition position_id</param>
        /// <param name="position_name">AdPosition position_name</param>
        /// <param name="ad_width">AdPosition ad_width</param>
        /// <param name="ad_height">AdPosition ad_height</param>
        /// <param name="position_desc">AdPosition position_desc</param>
        /// <param name="position_style">AdPosition position_style</param>
        /// <param name="position_url">AdPosition position_url</param>
        /// <param name="position_type">AdPosition position_type</param>
        /// <param name="is_show_text">AdPosition is_show_text</param>
        public AdPositionInfo(System.Int32 position_id,System.String position_name,System.Int32 ad_width,System.Int32 ad_height,System.String position_desc,System.String position_style,System.String position_url,System.Int32 position_type,System.Boolean is_show_text) {
            this._position_id = position_id;
            this._position_name = position_name;
            this._ad_width = ad_width;
            this._ad_height = ad_height;
            this._position_desc = position_desc;
            this._position_style = position_style;
            this._position_url = position_url;
            this._position_type = position_type;
            this._is_show_text = is_show_text;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? position_id {
            get { return _position_id; }
            set { _position_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String position_name {
            get { return _position_name; }
            set { _position_name = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? ad_width {
            get { return _ad_width; }
            set { _ad_width = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? ad_height {
            get { return _ad_height; }
            set { _ad_height = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String position_desc {
            get { return _position_desc; }
            set { _position_desc = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String position_style {
            get { return _position_style; }
            set { _position_style = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String position_url {
            get { return _position_url; }
            set { _position_url = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? position_type {
            get { return _position_type; }
            set { _position_type = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_show_text {
            get { return _is_show_text; }
            set { _is_show_text = value; }
        }
        
    }
}