//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// CityStation实体
    /// </summary>
    [Serializable]
    public class CityStationInfo {

        // Internal member variables
        
        private System.Int32? _city_id;
        private System.String _name;
        private System.String _pinyin;
        private System.String _other;
        private System.Boolean? _is_enable;
        private System.DateTime? _date;
        private System.String _pagetitle;
        private System.String _pagekeywords;
        private System.String _pagedesc;

        /// <summary>
        /// Default constructor
        /// </summary>
        public CityStationInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="city_id">CityStation city_id</param>
        /// <param name="name">CityStation name</param>
        /// <param name="pinyin">CityStation pinyin</param>
        /// <param name="other">CityStation other</param>
        /// <param name="is_enable">CityStation is_enable</param>
        /// <param name="date">CityStation date</param>
        public CityStationInfo(System.Int32 city_id, System.String name, System.String pinyin, System.String other, System.Boolean is_enable, System.DateTime date, System.String pagetitle, System.String pagekeywords, System.String pagedesc)
        {
            this._city_id = city_id;
            this._name = name;
            this._pinyin = pinyin;
            this._other = other;
            this._is_enable = is_enable;
            this._date = date;
            this._pagetitle = pagetitle;
            this._pagekeywords = pagekeywords;
            this._pagedesc = pagedesc;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? city_id {
            get { return _city_id; }
            set { _city_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String name {
            get { return _name; }
            set { _name = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String pinyin {
            get { return _pinyin; }
            set { _pinyin = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String other {
            get { return _other; }
            set { _other = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_enable {
            get { return _is_enable; }
            set { _is_enable = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? date {
            get { return _date; }
            set { _date = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String pagetitle
        {
            get { return _pagetitle; }
            set { _pagetitle = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String pagekeywords
        {
            get { return _pagekeywords; }
            set { _pagekeywords = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String pagedesc
        {
            get { return _pagedesc; }
            set { _pagedesc = value; }
        }
        
    }
}