//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DY.Entity
{

    /// <summary>
    /// CmsCat实体
    /// </summary>
    [Serializable]
    public class CmsCatInfo
    {

        // Internal member variables

        private System.Int32? _cat_id;
        private System.Int32? _parent_id;
        private System.String _cat_name;
        private System.Int32? _cat_type;
        private System.Int32? _content_type;
        private System.Boolean? _show_in_nav;
        private System.Boolean? _is_review;
        private System.String _cat_path;
        private System.Int32? _cat_level;
        private System.Int32? _sort_order;
        private System.Int32? _page_size;
        private System.String _list_tlp;
        private System.String _info_tlp;
        private System.String _urlrewriter;
        private System.String _pagetitle;
        private System.String _pagekeywords;
        private System.String _pagedesc;
        private System.String _pic;
        private System.String _ms;
        private System.Boolean? _is_mobile;
        private System.String _en_cat_name;
        private List<CmsCatInfo> _children;  
        /// <summary>
        /// Default constructor
        /// </summary>
        public CmsCatInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="cat_id">CmsCat cat_id</param>
        /// <param name="parent_id">CmsCat parent_id</param>
        /// <param name="cat_name">CmsCat cat_name</param>
        /// <param name="cat_type">CmsCat cat_type</param>
        /// <param name="content_type">CmsCat content_type</param>
        /// <param name="show_in_nav">CmsCat show_in_nav</param>
        /// <param name="is_review">CmsCat is_review</param>
        /// <param name="cat_path">CmsCat cat_path</param>
        /// <param name="cat_level">CmsCat cat_level</param>
        /// <param name="sort_order">CmsCat sort_order</param>
        /// <param name="page_size">CmsCat page_size</param>
        /// <param name="list_tlp">CmsCat list_tlp</param>
        /// <param name="info_tlp">CmsCat info_tlp</param>
        /// <param name="urlrewriter">CmsCat urlrewriter</param>
        /// <param name="pagetitle">CmsCat pagetitle</param>
        /// <param name="pagekeywords">CmsCat pagekeywords</param>
        /// <param name="pagedesc">CmsCat pagedesc</param>
        /// <param name="pic">CmsCat pic</param>
        /// <param name="ms">CmsCat ms</param>
        /// <param name="is_mobile">CmsCat is_mobile</param>
        /// <param name="en_cat_name">CmsCat en_cat_name</param>
        public CmsCatInfo(System.Int32 cat_id, System.Int32 parent_id, System.String cat_name, System.Int32 cat_type, System.Int32 content_type, System.Boolean show_in_nav, System.Boolean is_review, System.String cat_path, System.Int32 cat_level, System.Int32 sort_order, System.Int32 page_size, System.String list_tlp, System.String info_tlp, System.String urlrewriter, System.String pagetitle, System.String pagekeywords, System.String pagedesc, System.String pic, System.String ms, System.Boolean is_mobile, System.String en_cat_name)
        {
            this._cat_id = cat_id;
            this._parent_id = parent_id;
            this._cat_name = cat_name;
            this._cat_type = cat_type;
            this._content_type = content_type;
            this._show_in_nav = show_in_nav;
            this._is_review = is_review;
            this._cat_path = cat_path;
            this._cat_level = cat_level;
            this._sort_order = sort_order;
            this._page_size = page_size;
            this._list_tlp = list_tlp;
            this._info_tlp = info_tlp;
            this._urlrewriter = urlrewriter;
            this._pagetitle = pagetitle;
            this._pagekeywords = pagekeywords;
            this._pagedesc = pagedesc;
            this._pic = pic;
            this._ms = ms;
            this._is_mobile = is_mobile;
            this._en_cat_name = en_cat_name;

        }

        /// <summary>
        /// 
        /// </summary>
        public List<CmsCatInfo> children
        {
            get { return _children; }
            set { _children = value; }
        }  
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? cat_id
        {
            get { return _cat_id; }
            set { _cat_id = value; }
        }

        /// <summary>
        /// 上级id
        /// </summary>
        public System.Int32? parent_id
        {
            get { return _parent_id; }
            set { _parent_id = value; }
        }

        /// <summary>
        /// 分类名称
        /// </summary>
        public System.String cat_name
        {
            get { return _cat_name; }
            set { _cat_name = value; }
        }

        /// <summary>
        /// 0为用户，1为系统
        /// </summary>
        public System.Int32? cat_type
        {
            get { return _cat_type; }
            set { _cat_type = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? content_type
        {
            get { return _content_type; }
            set { _content_type = value; }
        }

        /// <summary>
        /// 是否显示在导航栏
        /// </summary>
        public System.Boolean? show_in_nav
        {
            get { return _show_in_nav; }
            set { _show_in_nav = value; }
        }

        /// <summary>
        /// 该类下面的页面是否允许评论
        /// </summary>
        public System.Boolean? is_review
        {
            get { return _is_review; }
            set { _is_review = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String cat_path
        {
            get { return _cat_path; }
            set { _cat_path = value; }
        }

        /// <summary>
        /// 本类深度
        /// </summary>
        public System.Int32? cat_level
        {
            get { return _cat_level; }
            set { _cat_level = value; }
        }

        /// <summary>
        /// 排序
        /// </summary>
        public System.Int32? sort_order
        {
            get { return _sort_order; }
            set { _sort_order = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? page_size
        {
            get { return _page_size; }
            set { _page_size = value; }
        }

        /// <summary>
        /// 列表模板路径
        /// </summary>
        public System.String list_tlp
        {
            get { return _list_tlp; }
            set { _list_tlp = value; }
        }

        /// <summary>
        /// 详细页模板路径
        /// </summary>
        public System.String info_tlp
        {
            get { return _info_tlp; }
            set { _info_tlp = value; }
        }

        /// <summary>
        /// 自定义url地址
        /// </summary>
        public System.String urlrewriter
        {
            get { return _urlrewriter; }
            set { _urlrewriter = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String pagetitle
        {
            get { return _pagetitle; }
            set { _pagetitle = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String pagekeywords
        {
            get { return _pagekeywords; }
            set { _pagekeywords = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String pagedesc
        {
            get { return _pagedesc; }
            set { _pagedesc = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String pic
        {
            get { return _pic; }
            set { _pic = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String ms
        {
            get { return _ms; }
            set { _ms = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_mobile
        {
            get { return _is_mobile; }
            set { _is_mobile = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String en_cat_name
        {
            get { return _en_cat_name; }
            set { _en_cat_name = value; }
        }

    }
}
