//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity
{

    /// <summary>
    /// CmsLink实体
    /// </summary>
    [Serializable]
    public class CmsLinkInfo
    {

        // Internal member variables

        private System.Int32? _link_id;
        private System.Int32? _cms_id;
        private System.Int32? _link_goods_id;
        private System.Int32? _link_dowsload_id;
        private System.Boolean? _is_double;
        private System.Int32? _admin_id;
        private System.Int32? _type;

        /// <summary>
        /// Default constructor
        /// </summary>
        public CmsLinkInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="link_id">CmsLink link_id</param>
        /// <param name="cms_id">CmsLink cms_id</param>
        /// <param name="link_goods_id">CmsLink link_goods_id</param>
        /// <param name="link_dowsload_id">CmsLink link_dowsload_id</param>
        /// <param name="is_double">CmsLink is_double</param>
        /// <param name="admin_id">CmsLink admin_id</param>
        /// <param name="type">CmsLink type</param>
        public CmsLinkInfo(System.Int32 link_id, System.Int32 cms_id, System.Int32 link_goods_id, System.Int32 link_dowsload_id, System.Boolean is_double, System.Int32 admin_id, System.Int32 type)
        {
            this._link_id = link_id;
            this._cms_id = cms_id;
            this._link_goods_id = link_goods_id;
            this._link_dowsload_id = link_dowsload_id;
            this._is_double = is_double;
            this._admin_id = admin_id;
            this._type = type;

        }


        /// <summary>
        /// 
        /// </summary>
        public System.Int32? link_id
        {
            get { return _link_id; }
            set { _link_id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? cms_id
        {
            get { return _cms_id; }
            set { _cms_id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? link_goods_id
        {
            get { return _link_goods_id; }
            set { _link_goods_id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? link_dowsload_id
        {
            get { return _link_dowsload_id; }
            set { _link_dowsload_id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_double
        {
            get { return _is_double; }
            set { _is_double = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? admin_id
        {
            get { return _admin_id; }
            set { _admin_id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? type
        {
            get { return _type; }
            set { _type = value; }
        }

    }
}
