//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// Delivery实体
    /// </summary>
    [Serializable]
    public class DeliveryInfo {

        // Internal member variables
        
        private System.Int32? _delivery_id;
        private System.String _delivery_name;
        private System.String _delivery_desc;
        private System.Decimal? _delivery_price;
        private System.Boolean? _support_cod;
        private System.Boolean? _enabled;
        private System.Int32? _orderid;
        private System.Decimal? _free_price;
        private System.String _com;
        /// <summary>
        /// Default constructor
        /// </summary>
        public DeliveryInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="delivery_id">Delivery delivery_id</param>
        /// <param name="delivery_name">Delivery delivery_name</param>
        /// <param name="delivery_desc">Delivery delivery_desc</param>
        /// <param name="delivery_price">Delivery delivery_price</param>
        /// <param name="support_cod">Delivery support_cod</param>
        /// <param name="enabled">Delivery enabled</param>
        /// <param name="orderid">Delivery orderid</param>
        /// <param name="free_price">Delivery free_price</param>
        public DeliveryInfo(System.Int32 delivery_id,System.String delivery_name,System.String delivery_desc,System.Decimal delivery_price,System.Boolean support_cod,System.Boolean enabled,System.Int32 orderid,System.Decimal free_price,System.String com) {
            this._delivery_id = delivery_id;
            this._delivery_name = delivery_name;
            this._delivery_desc = delivery_desc;
            this._delivery_price = delivery_price;
            this._support_cod = support_cod;
            this._enabled = enabled;
            this._orderid = orderid;
            this._free_price = free_price;
            this._com = com;
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String com
        {
            get { return _com; }
            set { _com = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? delivery_id {
            get { return _delivery_id; }
            set { _delivery_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String delivery_name {
            get { return _delivery_name; }
            set { _delivery_name = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String delivery_desc {
            get { return _delivery_desc; }
            set { _delivery_desc = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Decimal? delivery_price {
            get { return _delivery_price; }
            set { _delivery_price = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? support_cod {
            get { return _support_cod; }
            set { _support_cod = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? enabled {
            get { return _enabled; }
            set { _enabled = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? orderid {
            get { return _orderid; }
            set { _orderid = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Decimal? free_price {
            get { return _free_price; }
            set { _free_price = value; }
        }
        
    }
}