//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity
{

    /// <summary>
    /// DeliveryAddress实体
    /// </summary>
    [Serializable]
    public class DeliveryAddressInfo
    {

        // Internal member variables

        private System.Int32? _id;
        private System.String _consignee;
        private System.Int32? _country;
        private System.Int32? _province;
        private System.Int32? _city;
        private System.Int32? _district;
        private System.String _address;
        private System.String _zipcode;
        private System.String _tel;
        private System.String _mobile;
        private System.String _email;
        private System.Boolean? _is_checked;
        private System.Int32? _userid;

        /// <summary>
        /// Default constructor
        /// </summary>
        public DeliveryAddressInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="id">DeliveryAddress id</param>
        /// <param name="consignee">DeliveryAddress consignee</param>
        /// <param name="country">DeliveryAddress country</param>
        /// <param name="province">DeliveryAddress province</param>
        /// <param name="city">DeliveryAddress city</param>
        /// <param name="district">DeliveryAddress district</param>
        /// <param name="address">DeliveryAddress address</param>
        /// <param name="zipcode">DeliveryAddress zipcode</param>
        /// <param name="tel">DeliveryAddress tel</param>
        /// <param name="mobile">DeliveryAddress mobile</param>
        /// <param name="email">DeliveryAddress email</param>
        /// <param name="is_checked">DeliveryAddress is_checked</param>
        /// <param name="userid">DeliveryAddress userid</param>
        public DeliveryAddressInfo(System.Int32 id, System.String consignee, System.Int32 country, System.Int32 province, System.Int32 city, System.Int32 district, System.String address, System.String zipcode, System.String tel, System.String mobile, System.String email, System.Boolean is_checked, System.Int32 userid)
        {
            this._id = id;
            this._consignee = consignee;
            this._country = country;
            this._province = province;
            this._city = city;
            this._district = district;
            this._address = address;
            this._zipcode = zipcode;
            this._tel = tel;
            this._mobile = mobile;
            this._email = email;
            this._is_checked = is_checked;
            this._userid = userid;

        }


        /// <summary>
        /// 
        /// </summary>
        public System.Int32? id
        {
            get { return _id; }
            set { _id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String consignee
        {
            get { return _consignee; }
            set { _consignee = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? country
        {
            get { return _country; }
            set { _country = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? province
        {
            get { return _province; }
            set { _province = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? city
        {
            get { return _city; }
            set { _city = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? district
        {
            get { return _district; }
            set { _district = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String address
        {
            get { return _address; }
            set { _address = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String zipcode
        {
            get { return _zipcode; }
            set { _zipcode = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String tel
        {
            get { return _tel; }
            set { _tel = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String mobile
        {
            get { return _mobile; }
            set { _mobile = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String email
        {
            get { return _email; }
            set { _email = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_checked
        {
            get { return _is_checked; }
            set { _is_checked = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? userid
        {
            get { return _userid; }
            set { _userid = value; }
        }

    }
}
