//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// DeliveryArea实体
    /// </summary>
    [Serializable]
    public class DeliveryAreaInfo {

        // Internal member variables
        
        private System.Int32? _shipping_area_id;
        private System.String _shipping_area_name;
        private System.Int32? _shipping_id;
        private System.Decimal? _basic_fee;
        private System.Decimal? _free_money;
        private System.String _configure;

        /// <summary>
        /// Default constructor
        /// </summary>
        public DeliveryAreaInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="shipping_area_id">DeliveryArea shipping_area_id</param>
        /// <param name="shipping_area_name">DeliveryArea shipping_area_name</param>
        /// <param name="shipping_id">DeliveryArea shipping_id</param>
        /// <param name="basic_fee">DeliveryArea basic_fee</param>
        /// <param name="free_money">DeliveryArea free_money</param>
        /// <param name="configure">DeliveryArea configure</param>
        public DeliveryAreaInfo(System.Int32 shipping_area_id,System.String shipping_area_name,System.Int32 shipping_id,System.Decimal basic_fee,System.Decimal free_money,System.String configure) {
            this._shipping_area_id = shipping_area_id;
            this._shipping_area_name = shipping_area_name;
            this._shipping_id = shipping_id;
            this._basic_fee = basic_fee;
            this._free_money = free_money;
            this._configure = configure;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? shipping_area_id {
            get { return _shipping_area_id; }
            set { _shipping_area_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String shipping_area_name {
            get { return _shipping_area_name; }
            set { _shipping_area_name = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? shipping_id {
            get { return _shipping_id; }
            set { _shipping_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Decimal? basic_fee {
            get { return _basic_fee; }
            set { _basic_fee = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Decimal? free_money {
            get { return _free_money; }
            set { _free_money = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String configure {
            get { return _configure; }
            set { _configure = value; }
        }
        
    }
}