//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DY.Entity {

    /// <summary>
    /// DownloadCategory实体
    /// </summary>
    [Serializable]
    public class DownloadCategoryInfo {

        // Internal member variables
        
        private System.Int32? _cat_id;
        private System.Int32? _parent_id;
        private System.Int32? _cat_type;
        private System.String _cat_name;
        private System.String _keywords;
        private System.String _cat_desc;
        private System.Int32? _sort_order;
        private System.Int32? _cat_level;
        private System.String _template_file;
        private System.String _template_detail_path;
        private System.Boolean? _show_in_nav;
        private System.Boolean? _is_review;
        private System.Boolean? _is_show;
        private System.Int32? _grade;
        private System.String _urlrewriter;
        private System.Boolean? _child_open;
        private System.String _ico;
        private System.Int32? _article_photo_height;
        private System.Int32? _article_photo_width;
        private System.String _link_url;
        private System.Int32? _pagesize;
        private List<DownloadCategoryInfo> _children;  
        /// <summary>
        /// Default constructor
        /// </summary>
        public DownloadCategoryInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="cat_id">DownloadCategory cat_id</param>
        /// <param name="parent_id">DownloadCategory parent_id</param>
        /// <param name="cat_type">DownloadCategory cat_type</param>
        /// <param name="cat_name">DownloadCategory cat_name</param>
        /// <param name="keywords">DownloadCategory keywords</param>
        /// <param name="cat_desc">DownloadCategory cat_desc</param>
        /// <param name="sort_order">DownloadCategory sort_order</param>
        /// <param name="cat_level">DownloadCategory cat_level</param>
        /// <param name="template_file">DownloadCategory template_file</param>
        /// <param name="template_detail_path">DownloadCategory template_detail_path</param>
        /// <param name="show_in_nav">DownloadCategory show_in_nav</param>
        /// <param name="is_review">DownloadCategory is_review</param>
        /// <param name="is_show">DownloadCategory is_show</param>
        /// <param name="grade">DownloadCategory grade</param>
        /// <param name="urlrewriter">DownloadCategory urlrewriter</param>
        /// <param name="child_open">DownloadCategory child_open</param>
        /// <param name="ico">DownloadCategory ico</param>
        /// <param name="article_photo_height">DownloadCategory article_photo_height</param>
        /// <param name="article_photo_width">DownloadCategory article_photo_width</param>
        /// <param name="link_url">DownloadCategory link_url</param>
        /// <param name="pagesize">DownloadCategory pagesize</param>
        public DownloadCategoryInfo(System.Int32 cat_id,System.Int32 parent_id,System.Int32 cat_type,System.String cat_name,System.String keywords,System.String cat_desc,System.Int32 sort_order,System.Int32 cat_level,System.String template_file,System.String template_detail_path,System.Boolean show_in_nav,System.Boolean is_review,System.Boolean is_show,System.Int32 grade,System.String urlrewriter,System.Boolean child_open,System.String ico,System.Int32 article_photo_height,System.Int32 article_photo_width,System.String link_url,System.Int32 pagesize) {
            this._cat_id = cat_id;
            this._parent_id = parent_id;
            this._cat_type = cat_type;
            this._cat_name = cat_name;
            this._keywords = keywords;
            this._cat_desc = cat_desc;
            this._sort_order = sort_order;
            this._cat_level = cat_level;
            this._template_file = template_file;
            this._template_detail_path = template_detail_path;
            this._show_in_nav = show_in_nav;
            this._is_review = is_review;
            this._is_show = is_show;
            this._grade = grade;
            this._urlrewriter = urlrewriter;
            this._child_open = child_open;
            this._ico = ico;
            this._article_photo_height = article_photo_height;
            this._article_photo_width = article_photo_width;
            this._link_url = link_url;
            this._pagesize = pagesize;
            
        }

        /// <summary>
        /// 
        /// </summary>
        public List<DownloadCategoryInfo> children
        {
            get { return _children; }
            set { _children = value; }
        }  
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? cat_id {
            get { return _cat_id; }
            set { _cat_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? parent_id {
            get { return _parent_id; }
            set { _parent_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? cat_type {
            get { return _cat_type; }
            set { _cat_type = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String cat_name {
            get { return _cat_name; }
            set { _cat_name = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String keywords {
            get { return _keywords; }
            set { _keywords = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String cat_desc {
            get { return _cat_desc; }
            set { _cat_desc = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? sort_order {
            get { return _sort_order; }
            set { _sort_order = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? cat_level {
            get { return _cat_level; }
            set { _cat_level = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String template_file {
            get { return _template_file; }
            set { _template_file = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String template_detail_path {
            get { return _template_detail_path; }
            set { _template_detail_path = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? show_in_nav {
            get { return _show_in_nav; }
            set { _show_in_nav = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_review {
            get { return _is_review; }
            set { _is_review = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_show {
            get { return _is_show; }
            set { _is_show = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? grade {
            get { return _grade; }
            set { _grade = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String urlrewriter {
            get { return _urlrewriter; }
            set { _urlrewriter = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? child_open {
            get { return _child_open; }
            set { _child_open = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String ico {
            get { return _ico; }
            set { _ico = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? article_photo_height {
            get { return _article_photo_height; }
            set { _article_photo_height = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? article_photo_width {
            get { return _article_photo_width; }
            set { _article_photo_width = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String link_url {
            get { return _link_url; }
            set { _link_url = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? pagesize {
            get { return _pagesize; }
            set { _pagesize = value; }
        }
        
    }
}