//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// Download实体
    /// </summary>
    [Serializable]
    public class DownloadInfo {

        // Internal member variables
        
        private System.Int32? _down_id;
        private System.String _title;
        private System.String _keywords;
        private System.String _content;
        private System.DateTime? _inputtime;
        private System.Boolean? _is_enable;
        private System.Int32? _orderid;
        private System.String _url;
        private System.Int32? _rank;
        private System.String _author;
        private System.String _source;
        private System.String _des;
        private System.String _photo;
        private System.String _filesize;
        private System.String _filename;
        private System.Int32? _click_count;
        private System.String _urlrewriter;
        private System.Int32? _cat_id;
        private System.Boolean? _is_top;
        private System.String _seokeyword;
        private System.String _seodesc;
        private System.String _template_file;
        private System.DateTime? _showtime;
        private System.Int32? _is_reco;
        private System.String _soft_lan;
        private System.String _provider;
        private System.String _soft_authorize;
        private System.String _platform;
        private System.Int32? _no_reco;
        private System.String _seo_title;

        /// <summary>
        /// Default constructor
        /// </summary>
        public DownloadInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="down_id">Download down_id</param>
        /// <param name="title">Download title</param>
        /// <param name="keywords">Download keywords</param>
        /// <param name="content">Download content</param>
        /// <param name="inputtime">Download inputtime</param>
        /// <param name="is_enable">Download is_enable</param>
        /// <param name="orderid">Download orderid</param>
        /// <param name="url">Download url</param>
        /// <param name="rank">Download rank</param>
        /// <param name="author">Download author</param>
        /// <param name="source">Download source</param>
        /// <param name="des">Download des</param>
        /// <param name="photo">Download photo</param>
        /// <param name="filesize">Download filesize</param>
        /// <param name="filename">Download filename</param>
        /// <param name="click_count">Download click_count</param>
        /// <param name="urlrewriter">Download urlrewriter</param>
        /// <param name="cat_id">Download cat_id</param>
        /// <param name="is_top">Download is_top</param>
        /// <param name="seokeyword">Download seokeyword</param>
        /// <param name="seodesc">Download seodesc</param>
        /// <param name="template_file">Download template_file</param>
        /// <param name="showtime">Download showtime</param>
        /// <param name="is_reco">Download is_reco</param>
        /// <param name="soft_lan">Download soft_lan</param>
        /// <param name="provider">Download provider</param>
        /// <param name="soft_authorize">Download soft_authorize</param>
        /// <param name="platform">Download platform</param>
        /// <param name="no_reco">Download no_reco</param>
        /// <param name="seo_title">Download seo_title</param>
        public DownloadInfo(System.Int32 down_id,System.String title,System.String keywords,System.String content,System.DateTime inputtime,System.Boolean is_enable,System.Int32 orderid,System.String url,System.Int32 rank,System.String author,System.String source,System.String des,System.String photo,System.String filesize,System.String filename,System.Int32 click_count,System.String urlrewriter,System.Int32 cat_id,System.Boolean is_top,System.String seokeyword,System.String seodesc,System.String template_file,System.DateTime showtime,System.Int32 is_reco,System.String soft_lan,System.String provider,System.String soft_authorize,System.String platform,System.Int32 no_reco,System.String seo_title) {
            this._down_id = down_id;
            this._title = title;
            this._keywords = keywords;
            this._content = content;
            this._inputtime = inputtime;
            this._is_enable = is_enable;
            this._orderid = orderid;
            this._url = url;
            this._rank = rank;
            this._author = author;
            this._source = source;
            this._des = des;
            this._photo = photo;
            this._filesize = filesize;
            this._filename = filename;
            this._click_count = click_count;
            this._urlrewriter = urlrewriter;
            this._cat_id = cat_id;
            this._is_top = is_top;
            this._seokeyword = seokeyword;
            this._seodesc = seodesc;
            this._template_file = template_file;
            this._showtime = showtime;
            this._is_reco = is_reco;
            this._soft_lan = soft_lan;
            this._provider = provider;
            this._soft_authorize = soft_authorize;
            this._platform = platform;
            this._no_reco = no_reco;
            this._seo_title = seo_title;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? down_id {
            get { return _down_id; }
            set { _down_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String title {
            get { return _title; }
            set { _title = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String keywords {
            get { return _keywords; }
            set { _keywords = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String content {
            get { return _content; }
            set { _content = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? inputtime {
            get { return _inputtime; }
            set { _inputtime = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_enable {
            get { return _is_enable; }
            set { _is_enable = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? orderid {
            get { return _orderid; }
            set { _orderid = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String url {
            get { return _url; }
            set { _url = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? rank {
            get { return _rank; }
            set { _rank = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String author {
            get { return _author; }
            set { _author = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String source {
            get { return _source; }
            set { _source = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String des {
            get { return _des; }
            set { _des = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String photo {
            get { return _photo; }
            set { _photo = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String filesize {
            get { return _filesize; }
            set { _filesize = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String filename {
            get { return _filename; }
            set { _filename = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? click_count {
            get { return _click_count; }
            set { _click_count = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String urlrewriter {
            get { return _urlrewriter; }
            set { _urlrewriter = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? cat_id {
            get { return _cat_id; }
            set { _cat_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_top {
            get { return _is_top; }
            set { _is_top = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String seokeyword {
            get { return _seokeyword; }
            set { _seokeyword = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String seodesc {
            get { return _seodesc; }
            set { _seodesc = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String template_file {
            get { return _template_file; }
            set { _template_file = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? showtime {
            get { return _showtime; }
            set { _showtime = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? is_reco {
            get { return _is_reco; }
            set { _is_reco = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String soft_lan {
            get { return _soft_lan; }
            set { _soft_lan = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String provider {
            get { return _provider; }
            set { _provider = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String soft_authorize {
            get { return _soft_authorize; }
            set { _soft_authorize = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String platform {
            get { return _platform; }
            set { _platform = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? no_reco {
            get { return _no_reco; }
            set { _no_reco = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String seo_title {
            get { return _seo_title; }
            set { _seo_title = value; }
        }
        
    }
}