//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// ExchangeLog实体
    /// </summary>
    [Serializable]
    public class ExchangeLogInfo {

        // Internal member variables
        
        private System.Int32? _log_id;
        private System.String _name;
        private System.String _ip;
        private System.Int32? _type;
        private System.Int32? _card_id;
        private System.DateTime? _date;

        /// <summary>
        /// Default constructor
        /// </summary>
        public ExchangeLogInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="log_id">ExchangeLog log_id</param>
        /// <param name="name">ExchangeLog name</param>
        /// <param name="ip">ExchangeLog ip</param>
        /// <param name="type">ExchangeLog type</param>
        /// <param name="card_id">ExchangeLog card_id</param>
        /// <param name="date">ExchangeLog date</param>
        public ExchangeLogInfo(System.Int32 log_id,System.String name,System.String ip,System.Int32 type,System.Int32 card_id,System.DateTime date) {
            this._log_id = log_id;
            this._name = name;
            this._ip = ip;
            this._type = type;
            this._card_id = card_id;
            this._date = date;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? log_id {
            get { return _log_id; }
            set { _log_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String name {
            get { return _name; }
            set { _name = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String ip {
            get { return _ip; }
            set { _ip = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? type {
            get { return _type; }
            set { _type = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? card_id {
            get { return _card_id; }
            set { _card_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? date {
            get { return _date; }
            set { _date = value; }
        }
        
    }
}