//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// Favorites实体
    /// </summary>
    [Serializable]
    public class FavoritesInfo {

        // Internal member variables
        
        private System.Int32? _id;
        private System.Int32? _user_id;
        private System.Int32? _type;
        private System.Int32? _id_value;
        private System.String _remark;
        private System.DateTime? _add_time;

        /// <summary>
        /// Default constructor
        /// </summary>
        public FavoritesInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="id">Favorites id</param>
        /// <param name="user_id">Favorites user_id</param>
        /// <param name="type">Favorites type</param>
        /// <param name="id_value">Favorites id_value</param>
        /// <param name="remark">Favorites remark</param>
        /// <param name="add_time">Favorites add_time</param>
        public FavoritesInfo(System.Int32 id,System.Int32 user_id,System.Int32 type,System.Int32 id_value,System.String remark,System.DateTime add_time) {
            this._id = id;
            this._user_id = user_id;
            this._type = type;
            this._id_value = id_value;
            this._remark = remark;
            this._add_time = add_time;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? id {
            get { return _id; }
            set { _id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? user_id {
            get { return _user_id; }
            set { _user_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? type {
            get { return _type; }
            set { _type = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? id_value {
            get { return _id_value; }
            set { _id_value = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String remark {
            get { return _remark; }
            set { _remark = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? add_time {
            get { return _add_time; }
            set { _add_time = value; }
        }
        
    }
}