//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// Feedback实体
    /// </summary>
    [Serializable]
    public class FeedbackInfo {

        // Internal member variables
        
        private System.Int32? _msg_id;
        private System.Int32? _parent_id;
        private System.Int32? _user_id;
        private System.String _user_name;
        private System.String _user_email;
        private System.String _msg_title;
        private System.Int32? _msg_type;
        private System.String _msg_content;
        private System.DateTime? _msg_time;
        private System.String _msg_file;
        private System.Int32? _order_id;
        private System.Boolean? _is_show;
        private System.String _url;
        private System.String _user_qq;
        private System.String _ip;

        /// <summary>
        /// Default constructor
        /// </summary>
        public FeedbackInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="msg_id">Feedback msg_id</param>
        /// <param name="parent_id">Feedback parent_id</param>
        /// <param name="user_id">Feedback user_id</param>
        /// <param name="user_name">Feedback user_name</param>
        /// <param name="user_email">Feedback user_email</param>
        /// <param name="msg_title">Feedback msg_title</param>
        /// <param name="msg_type">Feedback msg_type</param>
        /// <param name="msg_content">Feedback msg_content</param>
        /// <param name="msg_time">Feedback msg_time</param>
        /// <param name="msg_file">Feedback msg_file</param>
        /// <param name="order_id">Feedback order_id</param>
        /// <param name="is_show">Feedback is_show</param>
        /// <param name="url">Feedback url</param>
        /// <param name="user_qq">Feedback user_qq</param>
        /// <param name="ip">Feedback ip</param>
        public FeedbackInfo(System.Int32 msg_id, System.Int32 parent_id, System.Int32 user_id, System.String user_name, System.String user_email, System.String msg_title, System.Int32 msg_type, System.String msg_content, System.DateTime msg_time, System.String msg_file, System.Int32 order_id, System.Boolean is_show, System.String url, System.String user_qq, System.String ip)
        {
            this._msg_id = msg_id;
            this._parent_id = parent_id;
            this._user_id = user_id;
            this._user_name = user_name;
            this._user_email = user_email;
            this._msg_title = msg_title;
            this._msg_type = msg_type;
            this._msg_content = msg_content;
            this._msg_time = msg_time;
            this._msg_file = msg_file;
            this._order_id = order_id;
            this._is_show = is_show;
            this._url = url;
            this._user_qq = user_qq;
            this._ip = ip;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? msg_id {
            get { return _msg_id; }
            set { _msg_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? parent_id {
            get { return _parent_id; }
            set { _parent_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? user_id {
            get { return _user_id; }
            set { _user_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String user_name {
            get { return _user_name; }
            set { _user_name = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String user_email {
            get { return _user_email; }
            set { _user_email = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String msg_title {
            get { return _msg_title; }
            set { _msg_title = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? msg_type {
            get { return _msg_type; }
            set { _msg_type = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String msg_content {
            get { return _msg_content; }
            set { _msg_content = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? msg_time {
            get { return _msg_time; }
            set { _msg_time = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String msg_file {
            get { return _msg_file; }
            set { _msg_file = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? order_id {
            get { return _order_id; }
            set { _order_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_show {
            get { return _is_show; }
            set { _is_show = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String url {
            get { return _url; }
            set { _url = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String user_qq {
            get { return _user_qq; }
            set { _user_qq = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String ip
        {
            get { return _ip; }
            set { _ip = value; }
        }
        
    }
}