//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// FormPosition实体
    /// </summary>
    [Serializable]
    public class FormPositionInfo {

        // Internal member variables
        
        private System.Int32? _position_id;
        private System.String _position_name;
        private System.String _position_desc;
        private System.Int32? _width;
        private System.Int32? _height;
        private System.String _position_classname;
        /// <summary>
        /// Default constructor
        /// </summary>
        public FormPositionInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="position_id">FormPosition position_id</param>
        /// <param name="position_name">FormPosition position_name</param>
        /// <param name="position_desc">FormPosition position_desc</param>
        /// <param name="width">FormPosition width</param>
        /// <param name="height">FormPosition height</param>
        public FormPositionInfo(System.Int32 position_id, System.String position_name, System.String position_desc, System.Int32 width, System.Int32 height, System.String position_classname)
        {
            this._position_id = position_id;
            this._position_name = position_name;
            this._position_desc = position_desc;
            this._width = width;
            this._height = height;
            this._position_classname = position_classname;
            
        }
        /// <summary>
        /// 
        /// </summary>
        public System.String position_classname
        {
            get { return _position_classname; }
            set { _position_classname = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? position_id {
            get { return _position_id; }
            set { _position_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String position_name {
            get { return _position_name; }
            set { _position_name = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String position_desc {
            get { return _position_desc; }
            set { _position_desc = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? width {
            get { return _width; }
            set { _width = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? height {
            get { return _height; }
            set { _height = value; }
        }
        
    }
}