//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// FriendLink实体
    /// </summary>
    [Serializable]
    public class FriendLinkInfo {

        // Internal member variables
        
        private System.Int32? _link_id;
        private System.String _link_name;
        private System.String _link_url;
        private System.String _link_logo;
        private System.Int32? _show_order;
        private System.Boolean? _is_tuijian;

        /// <summary>
        /// Default constructor
        /// </summary>
        public FriendLinkInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="link_id">FriendLink link_id</param>
        /// <param name="link_name">FriendLink link_name</param>
        /// <param name="link_url">FriendLink link_url</param>
        /// <param name="link_logo">FriendLink link_logo</param>
        /// <param name="show_order">FriendLink show_order</param>
        /// <param name="is_tuijian">FriendLink is_tuijian</param>
        public FriendLinkInfo(System.Int32 link_id,System.String link_name,System.String link_url,System.String link_logo,System.Int32 show_order,System.Boolean is_tuijian) {
            this._link_id = link_id;
            this._link_name = link_name;
            this._link_url = link_url;
            this._link_logo = link_logo;
            this._show_order = show_order;
            this._is_tuijian = is_tuijian;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? link_id {
            get { return _link_id; }
            set { _link_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String link_name {
            get { return _link_name; }
            set { _link_name = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String link_url {
            get { return _link_url; }
            set { _link_url = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String link_logo {
            get { return _link_logo; }
            set { _link_logo = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? show_order {
            get { return _show_order; }
            set { _show_order = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_tuijian {
            get { return _is_tuijian; }
            set { _is_tuijian = value; }
        }
        
    }
}