//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// GoodsUserPrice实体
    /// </summary>
    [Serializable]
    public class GoodsUserPriceInfo {

        // Internal member variables
        
        private System.Int32? _price_id;
        private System.Int32? _goods_id;
        private System.Int32? _user_rank;
        private System.Decimal? _user_price;

        /// <summary>
        /// Default constructor
        /// </summary>
        public GoodsUserPriceInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="price_id">GoodsUserPrice price_id</param>
        /// <param name="goods_id">GoodsUserPrice goods_id</param>
        /// <param name="user_rank">GoodsUserPrice user_rank</param>
        /// <param name="user_price">GoodsUserPrice user_price</param>
        public GoodsUserPriceInfo(System.Int32 price_id,System.Int32 goods_id,System.Int32 user_rank,System.Decimal user_price) {
            this._price_id = price_id;
            this._goods_id = goods_id;
            this._user_rank = user_rank;
            this._user_price = user_price;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? price_id {
            get { return _price_id; }
            set { _price_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? goods_id {
            get { return _goods_id; }
            set { _goods_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? user_rank {
            get { return _user_rank; }
            set { _user_rank = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Decimal? user_price {
            get { return _user_price; }
            set { _user_price = value; }
        }
        
    }
}