//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DY.Entity
{

    /// <summary>
    /// GoodsCategory实体
    /// </summary>
    [Serializable]
    public class GoodsCategoryInfo
    {

        // Internal member variables

        private System.Int32? _cat_id;
        private System.Int32? _parent_id;
        private System.String _cat_name;
        private System.String _cat_ico;
        private System.String _cat_desc;
        private System.String _cat_path;
        private System.String _list_tlp;
        private System.String _info_tlp;
        private System.Int32? _cat_level;
        private System.Int32? _cat_subcount;
        private System.String _measure_unit;
        private System.Boolean? _show_in_nav;
        private System.Boolean? _is_show;
        private System.Boolean? _is_hot;
        private System.Int32? _sort_order;
        private System.Int32? _page_size;
        private System.String _urlrewriter;
        private System.String _pagetitle;
        private System.String _pagekeywords;
        private System.String _pagedesc;
        private System.String _pricearea;
        private System.String _cat_name_en;
        private System.Boolean? _is_mobile;
        private System.String _cat_h_ico;
        private List<GoodsCategoryInfo> _children;  
        /// <summary>
        /// Default constructor
        /// </summary>
        public GoodsCategoryInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="cat_id">GoodsCategory cat_id</param>
        /// <param name="parent_id">GoodsCategory parent_id</param>
        /// <param name="cat_name">GoodsCategory cat_name</param>
        /// <param name="cat_ico">GoodsCategory cat_ico</param>
        /// <param name="cat_desc">GoodsCategory cat_desc</param>
        /// <param name="cat_path">GoodsCategory cat_path</param>
        /// <param name="list_tlp">GoodsCategory list_tlp</param>
        /// <param name="info_tlp">GoodsCategory info_tlp</param>
        /// <param name="cat_level">GoodsCategory cat_level</param>
        /// <param name="cat_subcount">GoodsCategory cat_subcount</param>
        /// <param name="measure_unit">GoodsCategory measure_unit</param>
        /// <param name="show_in_nav">GoodsCategory show_in_nav</param>
        /// <param name="is_show">GoodsCategory is_show</param>
        /// <param name="is_hot">GoodsCategory is_hot</param>
        /// <param name="sort_order">GoodsCategory sort_order</param>
        /// <param name="page_size">GoodsCategory page_size</param>
        /// <param name="urlrewriter">GoodsCategory urlrewriter</param>
        /// <param name="pagetitle">GoodsCategory pagetitle</param>
        /// <param name="pagekeywords">GoodsCategory pagekeywords</param>
        /// <param name="pagedesc">GoodsCategory pagedesc</param>
        /// <param name="pricearea">GoodsCategory pricearea</param>
        /// <param name="cat_name_en">GoodsCategory cat_name_en</param>
        /// <param name="is_mobile">GoodsCategory is_mobile</param>
        /// <param name="cat_h_ico">GoodsCategory cat_h_ico</param>
        public GoodsCategoryInfo(System.Int32 cat_id, System.Int32 parent_id, System.String cat_name, System.String cat_ico, System.String cat_desc, System.String cat_path, System.String list_tlp, System.String info_tlp, System.Int32 cat_level, System.Int32 cat_subcount, System.String measure_unit, System.Boolean show_in_nav, System.Boolean is_show, System.Boolean is_hot, System.Int32 sort_order, System.Int32 page_size, System.String urlrewriter, System.String pagetitle, System.String pagekeywords, System.String pagedesc, System.String pricearea, System.String cat_name_en, System.Boolean is_mobile, System.String cat_h_ico)
        {
            this._cat_id = cat_id;
            this._parent_id = parent_id;
            this._cat_name = cat_name;
            this._cat_ico = cat_ico;
            this._cat_desc = cat_desc;
            this._cat_path = cat_path;
            this._list_tlp = list_tlp;
            this._info_tlp = info_tlp;
            this._cat_level = cat_level;
            this._cat_subcount = cat_subcount;
            this._measure_unit = measure_unit;
            this._show_in_nav = show_in_nav;
            this._is_show = is_show;
            this._is_hot = is_hot;
            this._sort_order = sort_order;
            this._page_size = page_size;
            this._urlrewriter = urlrewriter;
            this._pagetitle = pagetitle;
            this._pagekeywords = pagekeywords;
            this._pagedesc = pagedesc;
            this._pricearea = pricearea;
            this._cat_name_en = cat_name_en;
            this._is_mobile = is_mobile;
            this._cat_h_ico = cat_h_ico;

        }

        /// <summary>
        /// 
        /// </summary>
        public List<GoodsCategoryInfo> children
        {
            get { return _children; }
            set { _children = value; }
        }  
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? cat_id
        {
            get { return _cat_id; }
            set { _cat_id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? parent_id
        {
            get { return _parent_id; }
            set { _parent_id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String cat_name
        {
            get { return _cat_name; }
            set { _cat_name = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String cat_ico
        {
            get { return _cat_ico; }
            set { _cat_ico = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String cat_desc
        {
            get { return _cat_desc; }
            set { _cat_desc = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String cat_path
        {
            get { return _cat_path; }
            set { _cat_path = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String list_tlp
        {
            get { return _list_tlp; }
            set { _list_tlp = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String info_tlp
        {
            get { return _info_tlp; }
            set { _info_tlp = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? cat_level
        {
            get { return _cat_level; }
            set { _cat_level = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? cat_subcount
        {
            get { return _cat_subcount; }
            set { _cat_subcount = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String measure_unit
        {
            get { return _measure_unit; }
            set { _measure_unit = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? show_in_nav
        {
            get { return _show_in_nav; }
            set { _show_in_nav = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_show
        {
            get { return _is_show; }
            set { _is_show = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_hot
        {
            get { return _is_hot; }
            set { _is_hot = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? sort_order
        {
            get { return _sort_order; }
            set { _sort_order = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? page_size
        {
            get { return _page_size; }
            set { _page_size = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String urlrewriter
        {
            get { return _urlrewriter; }
            set { _urlrewriter = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String pagetitle
        {
            get { return _pagetitle; }
            set { _pagetitle = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String pagekeywords
        {
            get { return _pagekeywords; }
            set { _pagekeywords = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String pagedesc
        {
            get { return _pagedesc; }
            set { _pagedesc = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String pricearea
        {
            get { return _pricearea; }
            set { _pricearea = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String cat_name_en
        {
            get { return _cat_name_en; }
            set { _cat_name_en = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_mobile
        {
            get { return _is_mobile; }
            set { _is_mobile = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String cat_h_ico
        {
            get { return _cat_h_ico; }
            set { _cat_h_ico = value; }
        }

    }
}
