//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace DY.Entity {

    /// <summary>
    /// GoodsGallery实体
    /// </summary>
    [Serializable]
    public class GoodsGalleryInfo {

        // Internal member variables
        
        private System.Int32? _img_id;
        private System.Int32? _goods_id;
        private System.String _img_desc;
        private System.String _goods_thumb;
        private System.String _goods_img;
        private System.String _info_img;
        private System.String _original_img;
        private System.Int32? _admin_user_id;
        private System.Int32? _order_id;
        private List<CmsCatInfo> _children;  
        /// <summary>
        /// Default constructor
        /// </summary>
        public GoodsGalleryInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="img_id">GoodsGallery img_id</param>
        /// <param name="goods_id">GoodsGallery goods_id</param>
        /// <param name="img_desc">GoodsGallery img_desc</param>
        /// <param name="goods_thumb">GoodsGallery goods_thumb</param>
        /// <param name="goods_img">GoodsGallery goods_img</param>
        /// <param name="info_img">GoodsGallery info_img</param>
        /// <param name="original_img">GoodsGallery original_img</param>
        /// <param name="admin_user_id">GoodsGallery admin_user_id</param>
        /// <param name="order_id">GoodsGallery order_id</param>
        public GoodsGalleryInfo(System.Int32 img_id,System.Int32 goods_id,System.String img_desc,System.String goods_thumb,System.String goods_img,System.String info_img,System.String original_img,System.Int32 admin_user_id,System.Int32 order_id) {
            this._img_id = img_id;
            this._goods_id = goods_id;
            this._img_desc = img_desc;
            this._goods_thumb = goods_thumb;
            this._goods_img = goods_img;
            this._info_img = info_img;
            this._original_img = original_img;
            this._admin_user_id = admin_user_id;
            this._order_id = order_id;
            
        }

        /// <summary>
        /// 
        /// </summary>
        public List<CmsCatInfo> children
        {
            get { return _children; }
            set { _children = value; }
        }  
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? img_id {
            get { return _img_id; }
            set { _img_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? goods_id {
            get { return _goods_id; }
            set { _goods_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String img_desc {
            get { return _img_desc; }
            set { _img_desc = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String goods_thumb {
            get { return _goods_thumb; }
            set { _goods_thumb = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String goods_img {
            get { return _goods_img; }
            set { _goods_img = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String info_img {
            get { return _info_img; }
            set { _info_img = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String original_img {
            get { return _original_img; }
            set { _original_img = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? admin_user_id {
            get { return _admin_user_id; }
            set { _admin_user_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? order_id {
            get { return _order_id; }
            set { _order_id = value; }
        }
        
    }
}