//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// GoodsSpecValues实体
    /// </summary>
    [Serializable]
    public class GoodsSpecValuesInfo {

        // Internal member variables
        
        private System.Int32? _spec_value_id;
        private System.Int32? _spec_id;
        private System.String _spec_value;
        private System.String _alias;
        private System.String _spec_image;
        private System.Int32? _p_order;
        private System.Int32? _supplier_id;
        private System.Int32? _supplier_spec_value_id;

        /// <summary>
        /// Default constructor
        /// </summary>
        public GoodsSpecValuesInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="spec_value_id">GoodsSpecValues spec_value_id</param>
        /// <param name="spec_id">GoodsSpecValues spec_id</param>
        /// <param name="spec_value">GoodsSpecValues spec_value</param>
        /// <param name="alias">GoodsSpecValues alias</param>
        /// <param name="spec_image">GoodsSpecValues spec_image</param>
        /// <param name="p_order">GoodsSpecValues p_order</param>
        /// <param name="supplier_id">GoodsSpecValues supplier_id</param>
        /// <param name="supplier_spec_value_id">GoodsSpecValues supplier_spec_value_id</param>
        public GoodsSpecValuesInfo(System.Int32 spec_value_id,System.Int32 spec_id,System.String spec_value,System.String alias,System.String spec_image,System.Int32 p_order,System.Int32 supplier_id,System.Int32 supplier_spec_value_id) {
            this._spec_value_id = spec_value_id;
            this._spec_id = spec_id;
            this._spec_value = spec_value;
            this._alias = alias;
            this._spec_image = spec_image;
            this._p_order = p_order;
            this._supplier_id = supplier_id;
            this._supplier_spec_value_id = supplier_spec_value_id;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? spec_value_id {
            get { return _spec_value_id; }
            set { _spec_value_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? spec_id {
            get { return _spec_id; }
            set { _spec_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String spec_value {
            get { return _spec_value; }
            set { _spec_value = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String alias {
            get { return _alias; }
            set { _alias = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String spec_image {
            get { return _spec_image; }
            set { _spec_image = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? p_order {
            get { return _p_order; }
            set { _p_order = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? supplier_id {
            get { return _supplier_id; }
            set { _supplier_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? supplier_spec_value_id {
            get { return _supplier_spec_value_id; }
            set { _supplier_spec_value_id = value; }
        }
        
    }
}