//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity
{

    /// <summary>
    /// JobDepartment实体
    /// </summary>
    [Serializable]
    public class JobDepartmentInfo
    {

        // Internal member variables

        private System.Int32? _department_id;
        private System.String _department_name;
        private System.Int32? _sort_order;

        /// <summary>
        /// Default constructor
        /// </summary>
        public JobDepartmentInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="department_id">JobDepartment department_id</param>
        /// <param name="department_name">JobDepartment department_name</param>
        /// <param name="sort_order">JobDepartment sort_order</param>
        public JobDepartmentInfo(System.Int32 department_id, System.String department_name, System.Int32 sort_order)
        {
            this._department_id = department_id;
            this._department_name = department_name;
            this._sort_order = sort_order;

        }


        /// <summary>
        /// 
        /// </summary>
        public System.Int32? department_id
        {
            get { return _department_id; }
            set { _department_id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String department_name
        {
            get { return _department_name; }
            set { _department_name = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? sort_order
        {
            get { return _sort_order; }
            set { _sort_order = value; }
        }

    }
}
