//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// Keywords实体
    /// </summary>
    [Serializable]
    public class KeywordsInfo {

        // Internal member variables
        
        private System.Int32? _id;
        private System.String _name;
        private System.String _url;
        private System.String _content;

        /// <summary>
        /// Default constructor
        /// </summary>
        public KeywordsInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="id">Keywords id</param>
        /// <param name="name">Keywords name</param>
        /// <param name="url">Keywords url</param>
        /// <param name="content">Keywords content</param>
        public KeywordsInfo(System.Int32 id,System.String name,System.String url,System.String content) {
            this._id = id;
            this._name = name;
            this._url = url;
            this._content = content;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? id {
            get { return _id; }
            set { _id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String name {
            get { return _name; }
            set { _name = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String url {
            get { return _url; }
            set { _url = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String content {
            get { return _content; }
            set { _content = value; }
        }
        
    }
}