//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity
{

    /// <summary>
    /// CtmonLbs实体
    /// </summary>
    [Serializable]
    public class LbsInfo
    {

        // Internal member variables

        private System.Int32? _id;
        private System.String _title;
        private System.Int32? _regionid;
        private System.Int32? _cityid;
        private System.Int32? _districtid;
        private System.String _address;
        private System.String _tel;
        private System.String _pic;
        private System.String _des;
        private System.String _xposition;
        private System.String _yposition;
        private System.String _type;
        private System.Int32? _order_id;


        /// <summary>
        /// Default constructor
        /// </summary>
        public LbsInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="id">CtmonLbs id</param>
        /// <param name="title">CtmonLbs title</param>
        /// <param name="regionid">CtmonLbs regionid</param>
        /// <param name="cityid">CtmonLbs cityid</param>
        /// <param name="districtid">CtmonLbs districtid</param>
        /// <param name="address">CtmonLbs address</param>
        /// <param name="tel">CtmonLbs tel</param>
        /// <param name="pic">CtmonLbs pic</param>
        /// <param name="des">CtmonLbs des</param>
        /// <param name="xposition">CtmonLbs xposition</param>
        /// <param name="yposition">CtmonLbs yposition</param>
        /// <param name="type">CtmonLbs type</param>
        public LbsInfo(System.Int32 id, System.String title, System.Int32 regionid, System.Int32 cityid, System.Int32 districtid, System.String address, System.String tel, System.String pic, System.String des, System.String xposition, System.String yposition, System.String type, System.Int32 order_id)
        {
            this._id = id;
            this._title = title;
            this._regionid = regionid;
            this._cityid = cityid;
            this._districtid = districtid;
            this._address = address;
            this._tel = tel;
            this._pic = pic;
            this._des = des;
            this._xposition = xposition;
            this._yposition = yposition;
            this._type = type;
            this._order_id = order_id;

        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? order_id
        {
            get { return _order_id; }
            set { _order_id = value; }
        }
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? id
        {
            get { return _id; }
            set { _id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String title
        {
            get { return _title; }
            set { _title = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? regionid
        {
            get { return _regionid; }
            set { _regionid = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? cityid
        {
            get { return _cityid; }
            set { _cityid = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? districtid
        {
            get { return _districtid; }
            set { _districtid = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String address
        {
            get { return _address; }
            set { _address = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String tel
        {
            get { return _tel; }
            set { _tel = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String pic
        {
            get { return _pic; }
            set { _pic = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String des
        {
            get { return _des; }
            set { _des = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String xposition
        {
            get { return _xposition; }
            set { _xposition = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String yposition
        {
            get { return _yposition; }
            set { _yposition = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String type
        {
            get { return _type; }
            set { _type = value; }
        }

    }
}
