//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// Payment实体
    /// </summary>
    [Serializable]
    public class PaymentInfo {

        // Internal member variables
        
        private System.Int32? _pay_id;
        private System.String _pay_code;
        private System.String _pay_name;
        private System.String _pay_fee;
        private System.String _pay_desc;
        private System.Int32? _pay_order;
        private System.String _pay_config;
        private System.Boolean? _enabled;
        private System.Boolean? _is_cod;
        private System.Boolean? _is_online;
        private System.Boolean? _is_cz;
        private System.Boolean? _is_czyh;

        /// <summary>
        /// Default constructor
        /// </summary>
        public PaymentInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="pay_id">Payment pay_id</param>
        /// <param name="pay_code">Payment pay_code</param>
        /// <param name="pay_name">Payment pay_name</param>
        /// <param name="pay_fee">Payment pay_fee</param>
        /// <param name="pay_desc">Payment pay_desc</param>
        /// <param name="pay_order">Payment pay_order</param>
        /// <param name="pay_config">Payment pay_config</param>
        /// <param name="enabled">Payment enabled</param>
        /// <param name="is_cod">Payment is_cod</param>
        /// <param name="is_online">Payment is_online</param>
        /// <param name="is_cz">Payment is_cz</param>
        /// <param name="is_czyh">Payment is_czyh</param>
        public PaymentInfo(System.Int32 pay_id,System.String pay_code,System.String pay_name,System.String pay_fee,System.String pay_desc,System.Int32 pay_order,System.String pay_config,System.Boolean enabled,System.Boolean is_cod,System.Boolean is_online,System.Boolean is_cz,System.Boolean is_czyh) {
            this._pay_id = pay_id;
            this._pay_code = pay_code;
            this._pay_name = pay_name;
            this._pay_fee = pay_fee;
            this._pay_desc = pay_desc;
            this._pay_order = pay_order;
            this._pay_config = pay_config;
            this._enabled = enabled;
            this._is_cod = is_cod;
            this._is_online = is_online;
            this._is_cz = is_cz;
            this._is_czyh = is_czyh;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? pay_id {
            get { return _pay_id; }
            set { _pay_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String pay_code {
            get { return _pay_code; }
            set { _pay_code = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String pay_name {
            get { return _pay_name; }
            set { _pay_name = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String pay_fee {
            get { return _pay_fee; }
            set { _pay_fee = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String pay_desc {
            get { return _pay_desc; }
            set { _pay_desc = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? pay_order {
            get { return _pay_order; }
            set { _pay_order = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String pay_config {
            get { return _pay_config; }
            set { _pay_config = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? enabled {
            get { return _enabled; }
            set { _enabled = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_cod {
            get { return _is_cod; }
            set { _is_cod = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_online {
            get { return _is_online; }
            set { _is_online = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_cz {
            get { return _is_cz; }
            set { _is_cz = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_czyh {
            get { return _is_czyh; }
            set { _is_czyh = value; }
        }
        
    }
}