//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace CShop.Entity {

    /// <summary>
    /// Promotion实体
    /// </summary>
    [Serializable]
    public class PromotionInfo {

        // Internal member variables
        
        private System.Int32? _id;
        private System.Int32? _pid;
        private System.String _website;
        private System.String _remark;
        private System.DateTime? _input_time;
        private System.Decimal? _cost;
        private System.Boolean? _is_default;

        /// <summary>
        /// Default constructor
        /// </summary>
        public PromotionInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="id">Promotion id</param>
        /// <param name="pid">Promotion pid</param>
        /// <param name="website">Promotion website</param>
        /// <param name="remark">Promotion remark</param>
        /// <param name="input_time">Promotion input_time</param>
        /// <param name="cost">Promotion cost</param>
        /// <param name="is_default">Promotion is_default</param>
        public PromotionInfo(System.Int32 id,System.Int32 pid,System.String website,System.String remark,System.DateTime input_time,System.Decimal cost,System.Boolean is_default) {
            this._id = id;
            this._pid = pid;
            this._website = website;
            this._remark = remark;
            this._input_time = input_time;
            this._cost = cost;
            this._is_default = is_default;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? id {
            get { return _id; }
            set { _id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? pid {
            get { return _pid; }
            set { _pid = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String website {
            get { return _website; }
            set { _website = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String remark {
            get { return _remark; }
            set { _remark = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? input_time {
            get { return _input_time; }
            set { _input_time = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Decimal? cost {
            get { return _cost; }
            set { _cost = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_default {
            get { return _is_default; }
            set { _is_default = value; }
        }
        
    }
}