//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// RegFieldsValue实体
    /// </summary>
    [Serializable]
    public class RegFieldsValueInfo {

        // Internal member variables
        
        private System.Int32? _id;
        private System.Int32? _user_id;
        private System.Int32? _reg_field_id;
        private System.String _field_value;

        /// <summary>
        /// Default constructor
        /// </summary>
        public RegFieldsValueInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="id">RegFieldsValue id</param>
        /// <param name="user_id">RegFieldsValue user_id</param>
        /// <param name="reg_field_id">RegFieldsValue reg_field_id</param>
        /// <param name="field_value">RegFieldsValue field_value</param>
        public RegFieldsValueInfo(System.Int32 id,System.Int32 user_id,System.Int32 reg_field_id,System.String field_value) {
            this._id = id;
            this._user_id = user_id;
            this._reg_field_id = reg_field_id;
            this._field_value = field_value;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? id {
            get { return _id; }
            set { _id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? user_id {
            get { return _user_id; }
            set { _user_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? reg_field_id {
            get { return _reg_field_id; }
            set { _reg_field_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String field_value {
            get { return _field_value; }
            set { _field_value = value; }
        }
        
    }
}