//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// Robots实体
    /// </summary>
    [Serializable]
    public class RobotsInfo {

        // Internal member variables
        
        private System.Int32? _id;
        private System.String _url;
        private System.String _robots;
        private System.String _ip;
        private System.DateTime? _date;

        /// <summary>
        /// Default constructor
        /// </summary>
        public RobotsInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="id">Robots id</param>
        /// <param name="url">Robots url</param>
        /// <param name="robots">Robots robots</param>
        /// <param name="date">Robots date</param>
        public RobotsInfo(System.Int32 id, System.String url, System.String robots, System.DateTime date, System.String ip)
        {
            this._id = id;
            this._url = url;
            this._robots = robots;
            this._date = date;
            this._ip = ip;
            
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String ip
        {
            get { return _ip; }
            set { _ip = value; }
        }
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? id {
            get { return _id; }
            set { _id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String url {
            get { return _url; }
            set { _url = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String robots {
            get { return _robots; }
            set { _robots = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? date {
            get { return _date; }
            set { _date = value; }
        }
        
    }
}