//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// Tpcomments实体
    /// </summary>
    [Serializable]
    public class TpcommentsInfo {

        // Internal member variables
        
        private System.Int32? _id;
        private System.String _log_id;
        private System.String _user_id;
        private System.String _post_id;
        private System.String _thread_id;
        private System.String _thread_key;
        private System.String _author_id;
        private System.String _author_name;
        private System.String _ip;
        private System.DateTime? _created_at;
        private System.String _message;
        private System.String _parent_id;
        private System.String _action;
        /// <summary>
        /// Default constructor
        /// </summary>
        public TpcommentsInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="id">Tpcomments id</param>
        /// <param name="log_id">Tpcomments log_id</param>
        /// <param name="user_id">Tpcomments user_id</param>
        /// <param name="post_id">Tpcomments post_id</param>
        /// <param name="thread_id">Tpcomments thread_id</param>
        /// <param name="thread_key">Tpcomments thread_key</param>
        /// <param name="author_id">Tpcomments author_id</param>
        /// <param name="author_name">Tpcomments author_name</param>
        /// <param name="ip">Tpcomments ip</param>
        /// <param name="created_at">Tpcomments created_at</param>
        /// <param name="message">Tpcomments message</param>
        /// <param name="parent_id">Tpcomments parent_id</param>
        public TpcommentsInfo(System.Int32 id, System.String log_id, System.String user_id, System.String post_id, System.String thread_id, System.String thread_key, System.String author_id, System.String author_name, System.String ip, System.DateTime created_at, System.String message, System.String parent_id, System.String action)
        {
            this._id = id;
            this._log_id = log_id;
            this._user_id = user_id;
            this._post_id = post_id;
            this._thread_id = thread_id;
            this._thread_key = thread_key;
            this._author_id = author_id;
            this._author_name = author_name;
            this._ip = ip;
            this._created_at = created_at;
            this._message = message;
            this._parent_id = parent_id;
            this._action = action;
        }


        /// <summary>
        /// 
        /// </summary>
        public System.String action
        {
            get { return _action; }
            set { _action = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? id {
            get { return _id; }
            set { _id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String log_id {
            get { return _log_id; }
            set { _log_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String user_id {
            get { return _user_id; }
            set { _user_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String post_id {
            get { return _post_id; }
            set { _post_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String thread_id {
            get { return _thread_id; }
            set { _thread_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String thread_key {
            get { return _thread_key; }
            set { _thread_key = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String author_id {
            get { return _author_id; }
            set { _author_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String author_name {
            get { return _author_name; }
            set { _author_name = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String ip {
            get { return _ip; }
            set { _ip = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? created_at {
            get { return _created_at; }
            set { _created_at = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String message {
            get { return _message; }
            set { _message = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String parent_id {
            get { return _parent_id; }
            set { _parent_id = value; }
        }
        
    }
}