
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace DY.Entity
{
    /// <summary>
    /// UrlrewriteConfig实体
    /// </summary>
    [Serializable]
    public class UrlrewriteConfigInfo
    {
        // Internal member variables
        private string _article;
        private string _article_detail;
        private string _download;
        private string _download_detail;
        private string _html;
        private string _html_article;
        private string _html_article_detail;
        private string _html_download;
        private string _html_download_detail;
        private string _html_index;
        private string _html_page;
        private string _html_product;
        private string _html_product_detail;
        private string _html_suffix;
        private string _http;
        private string _page;
        private string _product;
        private string _product_detail;
        private string _search;



        /// <summary>
        /// 伪静态（搜索页）
        /// </summary>
        public string search
        {
            get { return _search; }
            set { _search = value; }
        }


        /// <summary>
        /// 伪静态（产品详细）
        /// </summary>
        public string product_detail
        {
            get { return _product_detail; }
            set { _product_detail = value; }
        }


        /// <summary>
        /// 伪静态（产品分类）
        /// </summary>
        public string product
        {
            get { return _product; }
            set { _product = value; }
        }


        /// <summary>
        /// 伪静态（单页）
        /// </summary>
        public string page
        {
            get { return _page; }
            set { _page = value; }
        }


        /// <summary>
        /// 协议类型
        /// </summary>
        public string http
        {
            get { return _http; }
            set { _http = value; }
        }


        /// <summary>
        /// 静态地址后缀名
        /// </summary>
        public string html_suffix
        {
            get { return _html_suffix; }
            set { _html_suffix = value; }
        }


        /// <summary>
        /// 静态地址（产品详细）
        /// </summary>
        public string html_product_detail
        {
            get { return _html_product_detail; }
            set { _html_product_detail = value; }
        }


        /// <summary>
        /// 静态地址（产品分类）
        /// </summary>
        public string html_product
        {
            get { return _html_product; }
            set { _html_product = value; }
        }


        /// <summary>
        /// 静态地址（单页）
        /// </summary>
        public string html_page
        {
            get { return _html_page; }
            set { _html_page = value; }
        }


        /// <summary>
        /// 静态地址（首页）
        /// </summary>
        public string html_index
        {
            get { return _html_index; }
            set { _html_index = value; }
        }


        /// <summary>
        ///  静态地址(下载详细页)
        /// </summary>
        public string html_download_detail
        {
            get { return _html_download_detail; }
            set { _html_download_detail = value; }
        }


        /// <summary>
        /// 静态地址(下载分类)
        /// </summary>
        public string html_download
        {
            get { return _html_download; }
            set { _html_download = value; }
        }


        /// <summary>
        /// 静态地址(详细页)
        /// </summary>
        public string html_article_detail
        {
            get { return _html_article_detail; }
            set { _html_article_detail = value; }
        }


        /// <summary>
        /// 静态地址(分类)
        /// </summary>
        public string html_article
        {
            get { return _html_article; }
            set { _html_article = value; }
        }


        /// <summary>
        /// 静态路径
        /// </summary>
        public string html
        {
            get { return _html; }
            set { _html = value; }
        }


        /// <summary>
        /// 下载详细页
        /// </summary>
        public string download_detail
        {
            get { return _download_detail; }
            set { _download_detail = value; }
        }

        /// <summary>
        /// 下载列表页
        /// </summary>
        public string download
        {
            get { return _download; }
            set { _download = value; }
        }

        /// <summary>
        /// 资讯文章内容页
        /// </summary>
        public string article_detail
        {
            get { return _article_detail; }
            set { _article_detail = value; }
        }

        /// <summary>
        /// 资讯文章列表页
        /// </summary>
        public string article
        {
            get { return _article; }
            set { _article = value; }
        }
       
       
    }
}