//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// UserRank实体
    /// </summary>
    [Serializable]
    public class UserRankInfo {

        // Internal member variables
        
        private System.Int32? _rank_id;
        private System.String _rank_name;
        private System.Int32? _min_points;
        private System.Int32? _max_points;
        private System.Int32? _discount;
        private System.Boolean? _show_price;
        private System.Boolean? _special_rank;

        /// <summary>
        /// Default constructor
        /// </summary>
        public UserRankInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="rank_id">UserRank rank_id</param>
        /// <param name="rank_name">UserRank rank_name</param>
        /// <param name="min_points">UserRank min_points</param>
        /// <param name="max_points">UserRank max_points</param>
        /// <param name="discount">UserRank discount</param>
        /// <param name="show_price">UserRank show_price</param>
        /// <param name="special_rank">UserRank special_rank</param>
        public UserRankInfo(System.Int32 rank_id,System.String rank_name,System.Int32 min_points,System.Int32 max_points,System.Int32 discount,System.Boolean show_price,System.Boolean special_rank) {
            this._rank_id = rank_id;
            this._rank_name = rank_name;
            this._min_points = min_points;
            this._max_points = max_points;
            this._discount = discount;
            this._show_price = show_price;
            this._special_rank = special_rank;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? rank_id {
            get { return _rank_id; }
            set { _rank_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String rank_name {
            get { return _rank_name; }
            set { _rank_name = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? min_points {
            get { return _min_points; }
            set { _min_points = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? max_points {
            get { return _max_points; }
            set { _max_points = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? discount {
            get { return _discount; }
            set { _discount = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? show_price {
            get { return _show_price; }
            set { _show_price = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? special_rank {
            get { return _special_rank; }
            set { _special_rank = value; }
        }
        
    }
}