//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity
{

    /// <summary>
    /// UserWithdrawals实体
    /// </summary>
    [Serializable]
    public class UserWithdrawalsInfo
    {

        // Internal member variables

        private System.Int32? _withdrawals_id;
        private System.String _name;
        private System.String _blank;
        private System.Decimal? _money;
        private System.String _account;
        private System.DateTime? _date;
        private System.Boolean? _is_verified;
        private System.Int32? _user_id;
        private System.Int32? _admin_id;
        private System.Int32? _state;
        private System.String _des;
        private System.String _admin_user;

        /// <summary>
        /// Default constructor
        /// </summary>
        public UserWithdrawalsInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="withdrawals_id">UserWithdrawals withdrawals_id</param>
        /// <param name="name">UserWithdrawals name</param>
        /// <param name="blank">UserWithdrawals blank</param>
        /// <param name="money">UserWithdrawals money</param>
        /// <param name="account">UserWithdrawals account</param>
        /// <param name="date">UserWithdrawals date</param>
        /// <param name="is_verified">UserWithdrawals is_verified</param>
        /// <param name="user_id">UserWithdrawals user_id</param>
        /// <param name="admin_id">UserWithdrawals admin_id</param>
        /// <param name="state">UserWithdrawals state</param>
        /// <param name="des">UserWithdrawals des</param>
        /// <param name="admin_user">UserWithdrawals admin_user</param>
        public UserWithdrawalsInfo(System.Int32 withdrawals_id, System.String name, System.String blank, System.Decimal money, System.String account, System.DateTime date, System.Boolean is_verified, System.Int32 user_id, System.Int32 admin_id, System.Int32 state, System.String des, System.String admin_user)
        {
            this._withdrawals_id = withdrawals_id;
            this._name = name;
            this._blank = blank;
            this._money = money;
            this._account = account;
            this._date = date;
            this._is_verified = is_verified;
            this._user_id = user_id;
            this._admin_id = admin_id;
            this._state = state;
            this._des = des;
            this._admin_user = admin_user;

        }


        /// <summary>
        /// 
        /// </summary>
        public System.Int32? withdrawals_id
        {
            get { return _withdrawals_id; }
            set { _withdrawals_id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String name
        {
            get { return _name; }
            set { _name = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String blank
        {
            get { return _blank; }
            set { _blank = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Decimal? money
        {
            get { return _money; }
            set { _money = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String account
        {
            get { return _account; }
            set { _account = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? date
        {
            get { return _date; }
            set { _date = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? is_verified
        {
            get { return _is_verified; }
            set { _is_verified = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? user_id
        {
            get { return _user_id; }
            set { _user_id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? admin_id
        {
            get { return _admin_id; }
            set { _admin_id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? state
        {
            get { return _state; }
            set { _state = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String des
        {
            get { return _des; }
            set { _des = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String admin_user
        {
            get { return _admin_user; }
            set { _admin_user = value; }
        }

    }
}
