//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// VoteOption实体
    /// </summary>
    [Serializable]
    public class VoteOptionInfo {

        // Internal member variables
        
        private System.Int32? _option_id;
        private System.Int32? _vote_id;
        private System.String _option_name;
        private System.Int32? _option_count;

        /// <summary>
        /// Default constructor
        /// </summary>
        public VoteOptionInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="option_id">VoteOption option_id</param>
        /// <param name="vote_id">VoteOption vote_id</param>
        /// <param name="option_name">VoteOption option_name</param>
        /// <param name="option_count">VoteOption option_count</param>
        public VoteOptionInfo(System.Int32 option_id,System.Int32 vote_id,System.String option_name,System.Int32 option_count) {
            this._option_id = option_id;
            this._vote_id = vote_id;
            this._option_name = option_name;
            this._option_count = option_count;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? option_id {
            get { return _option_id; }
            set { _option_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? vote_id {
            get { return _vote_id; }
            set { _vote_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String option_name {
            get { return _option_name; }
            set { _option_name = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? option_count {
            get { return _option_count; }
            set { _option_count = value; }
        }
        
    }
}