//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity {

    /// <summary>
    /// VoteLog实体
    /// </summary>
    [Serializable]
    public class VoteLogInfo {

        // Internal member variables
        
        private System.Int32? _log_id;
        private System.Int32? _vote_id;
        private System.String _ip_address;
        private System.DateTime? _vote_time;

        /// <summary>
        /// Default constructor
        /// </summary>
        public VoteLogInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="log_id">VoteLog log_id</param>
        /// <param name="vote_id">VoteLog vote_id</param>
        /// <param name="ip_address">VoteLog ip_address</param>
        /// <param name="vote_time">VoteLog vote_time</param>
        public VoteLogInfo(System.Int32 log_id,System.Int32 vote_id,System.String ip_address,System.DateTime vote_time) {
            this._log_id = log_id;
            this._vote_id = vote_id;
            this._ip_address = ip_address;
            this._vote_time = vote_time;
            
        }
        
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? log_id {
            get { return _log_id; }
            set { _log_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.Int32? vote_id {
            get { return _vote_id; }
            set { _vote_id = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.String ip_address {
            get { return _ip_address; }
            set { _ip_address = value; }
        }
        
        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? vote_time {
            get { return _vote_time; }
            set { _vote_time = value; }
        }
        
    }
}