//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity
{

    /// <summary>
    /// WeixinNews实体
    /// </summary>
    [Serializable]
    public class WeixinNewsInfo
    {

        // Internal member variables

        private System.Int32? _replay_id;
        private System.String _keyword;
        private System.Int32? _type;
        private System.String _title;
        private System.String _des;
        private System.String _pic;
        private System.String _content;
        private System.String _url;
        private System.DateTime? _date;
        private System.Boolean? _enabled;
        private System.Int32? _radio_type;
        private System.String _double_news;
        private System.Int32? _pid;

        /// <summary>
        /// Default constructor
        /// </summary>
        public WeixinNewsInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="replay_id">WeixinNews replay_id</param>
        /// <param name="keyword">WeixinNews keyword</param>
        /// <param name="type">WeixinNews type</param>
        /// <param name="title">WeixinNews title</param>
        /// <param name="des">WeixinNews des</param>
        /// <param name="pic">WeixinNews pic</param>
        /// <param name="content">WeixinNews content</param>
        /// <param name="url">WeixinNews url</param>
        /// <param name="date">WeixinNews date</param>
        /// <param name="enabled">WeixinNews enabled</param>
        /// <param name="radio_type">WeixinNews radio_type</param>
        /// <param name="double_news">WeixinNews double_news</param>
        /// <param name="pid">WeixinNews pid</param>
        public WeixinNewsInfo(System.Int32 replay_id, System.String keyword, System.Int32 type, System.String title, System.String des, System.String pic, System.String content, System.String url, System.DateTime date, System.Boolean enabled, System.Int32 radio_type, System.String double_news, System.Int32 pid)
        {
            this._replay_id = replay_id;
            this._keyword = keyword;
            this._type = type;
            this._title = title;
            this._des = des;
            this._pic = pic;
            this._content = content;
            this._url = url;
            this._date = date;
            this._enabled = enabled;
            this._radio_type = radio_type;
            this._double_news = double_news;
            this._pid = pid;

        }


        /// <summary>
        /// 
        /// </summary>
        public System.Int32? replay_id
        {
            get { return _replay_id; }
            set { _replay_id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String keyword
        {
            get { return _keyword; }
            set { _keyword = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? type
        {
            get { return _type; }
            set { _type = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String title
        {
            get { return _title; }
            set { _title = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String des
        {
            get { return _des; }
            set { _des = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String pic
        {
            get { return _pic; }
            set { _pic = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String content
        {
            get { return _content; }
            set { _content = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String url
        {
            get { return _url; }
            set { _url = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? date
        {
            get { return _date; }
            set { _date = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? enabled
        {
            get { return _enabled; }
            set { _enabled = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? radio_type
        {
            get { return _radio_type; }
            set { _radio_type = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String double_news
        {
            get { return _double_news; }
            set { _double_news = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? pid
        {
            get { return _pid; }
            set { _pid = value; }
        }

    }
}
