//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity
{

    /// <summary>
    /// WeixinUser实体
    /// </summary>
    [Serializable]
    public class WeixinUserInfo
    {

        // Internal member variables

        private System.Int32? _user_id;
        private System.Int32? _subscribe;
        private System.String _openid;
        private System.String _nickname;
        private System.Int32? _sex;
        private System.String _city;
        private System.String _country;
        private System.String _province;
        private System.String _language;
        private System.String _headimgurl;
        private System.DateTime? _subscribe_time;
        private System.Int32? _pid;
        private System.Int32? _uid;

        /// <summary>
        /// Default constructor
        /// </summary>
        public WeixinUserInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="user_id">WeixinUser user_id</param>
        /// <param name="subscribe">WeixinUser subscribe</param>
        /// <param name="openid">WeixinUser openid</param>
        /// <param name="nickname">WeixinUser nickname</param>
        /// <param name="sex">WeixinUser sex</param>
        /// <param name="city">WeixinUser city</param>
        /// <param name="country">WeixinUser country</param>
        /// <param name="province">WeixinUser province</param>
        /// <param name="language">WeixinUser language</param>
        /// <param name="headimgurl">WeixinUser headimgurl</param>
        /// <param name="subscribe_time">WeixinUser subscribe_time</param>
        /// <param name="pid">WeixinUser pid</param>
        /// <param name="uid">WeixinUser uid</param>
        public WeixinUserInfo(System.Int32 user_id, System.Int32 subscribe, System.String openid, System.String nickname, System.Int32 sex, System.String city, System.String country, System.String province, System.String language, System.String headimgurl, System.DateTime subscribe_time, System.Int32 pid, System.Int32 uid)
        {
            this._user_id = user_id;
            this._subscribe = subscribe;
            this._openid = openid;
            this._nickname = nickname;
            this._sex = sex;
            this._city = city;
            this._country = country;
            this._province = province;
            this._language = language;
            this._headimgurl = headimgurl;
            this._subscribe_time = subscribe_time;
            this._pid = pid;
            this._uid = uid;

        }


        /// <summary>
        /// 
        /// </summary>
        public System.Int32? user_id
        {
            get { return _user_id; }
            set { _user_id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? subscribe
        {
            get { return _subscribe; }
            set { _subscribe = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String openid
        {
            get { return _openid; }
            set { _openid = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String nickname
        {
            get { return _nickname; }
            set { _nickname = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? sex
        {
            get { return _sex; }
            set { _sex = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String city
        {
            get { return _city; }
            set { _city = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String country
        {
            get { return _country; }
            set { _country = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String province
        {
            get { return _province; }
            set { _province = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String language
        {
            get { return _language; }
            set { _language = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String headimgurl
        {
            get { return _headimgurl; }
            set { _headimgurl = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? subscribe_time
        {
            get { return _subscribe_time; }
            set { _subscribe_time = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? pid
        {
            get { return _pid; }
            set { _pid = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? uid
        {
            get { return _uid; }
            set { _uid = value; }
        }

    }
}
