//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity
{

    /// <summary>
    /// WeixinWord实体
    /// </summary>
    [Serializable]
    public class WeixinWordInfo
    {

        // Internal member variables

        private System.Int32? _mpword_id;
        private System.String _keyword;
        private System.Int32? _type;
        private System.String _content;
        private System.DateTime? _date;
        private System.Boolean? _enabled;
        private System.Int32? _pid;

        /// <summary>
        /// Default constructor
        /// </summary>
        public WeixinWordInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="mpword_id">WeixinWord mpword_id</param>
        /// <param name="keyword">WeixinWord keyword</param>
        /// <param name="type">WeixinWord type</param>
        /// <param name="content">WeixinWord content</param>
        /// <param name="date">WeixinWord date</param>
        /// <param name="enabled">WeixinWord enabled</param>
        /// <param name="pid">WeixinWord pid</param>
        public WeixinWordInfo(System.Int32 mpword_id, System.String keyword, System.Int32 type, System.String content, System.DateTime date, System.Boolean enabled, System.Int32 pid)
        {
            this._mpword_id = mpword_id;
            this._keyword = keyword;
            this._type = type;
            this._content = content;
            this._date = date;
            this._enabled = enabled;
            this._pid = pid;

        }


        /// <summary>
        /// 
        /// </summary>
        public System.Int32? mpword_id
        {
            get { return _mpword_id; }
            set { _mpword_id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String keyword
        {
            get { return _keyword; }
            set { _keyword = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? type
        {
            get { return _type; }
            set { _type = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String content
        {
            get { return _content; }
            set { _content = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? date
        {
            get { return _date; }
            set { _date = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? enabled
        {
            get { return _enabled; }
            set { _enabled = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? pid
        {
            get { return _pid; }
            set { _pid = value; }
        }

    }
}
