//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace DY.Entity
{

    /// <summary>
    /// WeixinMenu实体
    /// </summary>
    [Serializable]
    public class WeixinMenuInfo
    {

        // Internal member variables

        private System.Int32? _menu_id;
        private System.Int32? _parent_id;
        private System.String _name;
        private System.String _trigger_word;
        private System.Int32? _sort_order;
        private System.Boolean? _enabled;
        private System.DateTime? _data;
        private System.Int32? _pid;
        private System.String _menu_key;

        /// <summary>
        /// Default constructor
        /// </summary>
        public WeixinMenuInfo() { }

        /// <summary>
        /// Constructor with specified initial values
        /// </summary>
        /// <param name="menu_id">WeixinMenu menu_id</param>
        /// <param name="parent_id">WeixinMenu parent_id</param>
        /// <param name="name">WeixinMenu name</param>
        /// <param name="trigger_word">WeixinMenu trigger_word</param>
        /// <param name="sort_order">WeixinMenu sort_order</param>
        /// <param name="enabled">WeixinMenu enabled</param>
        /// <param name="data">WeixinMenu data</param>
        /// <param name="pid">WeixinMenu pid</param>
        /// <param name="menu_key">WeixinMenu menu_key</param>
        public WeixinMenuInfo(System.Int32 menu_id, System.Int32 parent_id, System.String name, System.String trigger_word, System.Int32 sort_order, System.Boolean enabled, System.DateTime data, System.Int32 pid, System.String menu_key)
        {
            this._menu_id = menu_id;
            this._parent_id = parent_id;
            this._name = name;
            this._trigger_word = trigger_word;
            this._sort_order = sort_order;
            this._enabled = enabled;
            this._data = data;
            this._pid = pid;
            this._menu_key = menu_key;

        }


        /// <summary>
        /// 
        /// </summary>
        public System.Int32? menu_id
        {
            get { return _menu_id; }
            set { _menu_id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? parent_id
        {
            get { return _parent_id; }
            set { _parent_id = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String name
        {
            get { return _name; }
            set { _name = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String trigger_word
        {
            get { return _trigger_word; }
            set { _trigger_word = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? sort_order
        {
            get { return _sort_order; }
            set { _sort_order = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Boolean? enabled
        {
            get { return _enabled; }
            set { _enabled = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.DateTime? data
        {
            get { return _data; }
            set { _data = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.Int32? pid
        {
            get { return _pid; }
            set { _pid = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public System.String menu_key
        {
            get { return _menu_key; }
            set { _menu_key = value; }
        }

    }
}
