//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Data.Common;
using System.Reflection;

using DY.Common;
using DY.Cache;
using DY.Data;
using DY.Entity;

namespace DY.Site
{
    public partial class SiteBLL
    {
        /// <summary>
        /// 根据条件查询表中所有数据
        /// </summary>
        /// <param name="FieldOrder">以逗号分隔的排序字段列表,可以指定在字段后面指定DESC/ASC用于指定排序顺序</param>
        /// <param name="Where">查询条件</param>
        /// <returns></returns>
        public static ArrayList GetEmailListAllList(string FieldOrder, string Where)
        {
            return GetEmailListAllList(FieldOrder,"*", Where);
        }
        /// <summary>
        /// 根据条件查询表中所有数据
        /// </summary>
        /// <param name="FieldOrder">以逗号分隔的排序字段列表,可以指定在字段后面指定DESC/ASC用于指定排序顺序</param>
        /// <param name="strFields">要查询的字段列表</param>
        /// <param name="Where">查询条件</param>
        /// <returns></returns>
        public static ArrayList GetEmailListAllList(string FieldOrder,string strFields, string Where)
        {
            ArrayList entityList = new ArrayList();
            using (IDataReader sdr = DatabaseProvider.GetInstance().GetAllData("email_list", strFields, FieldOrder, Where))
            {
                while (sdr.Read())
                {
                    EmailListInfo entity = new EmailListInfo();
                    ReaderToEntity(sdr, entity);
                    entityList.Add(entity);
                }
            }

            return entityList;
        }
        /// <summary>
        /// 获取EmailList分页列表数据
        /// </summary>
        /// <param name="PageCurrent">要显示的页码</param>
        /// <param name="PageSize">每页的大小(记录数)</param>
        /// <param name="Where">查询条件</param>
        /// <param name="ResultCount">总页数</param>
        /// <returns></returns>
        public static ArrayList GetEmailListList(int PageCurrent, int PageSize, string FieldOrder, string Where, out int ResultCount)
        {
            return GetEmailListList(PageCurrent, PageSize, "*", FieldOrder, Where, out ResultCount);
        }
        /// <summary>
        /// 获取EmailList分页列表数据
        /// </summary>
        /// <param name="PageCurrent">要显示的页码</param>
        /// <param name="PageSize">每页的大小(记录数)</param>
        /// <param name="Where">查询条件</param>
        /// <param name="ResultCount">总页数</param>
        /// <returns></returns>
        public static ArrayList GetEmailListList(int PageCurrent, int PageSize, string strFields, string FieldOrder, string Where, out int ResultCount)
        {
            ArrayList entityList = new ArrayList();
            using (IDataReader sdr = DatabaseProvider.GetInstance().GetPagerData("email_list", "id", PageCurrent, PageSize, strFields, FieldOrder, Where, out ResultCount))
            {
                while (sdr.Read())
                {
                    EmailListInfo entity = new EmailListInfo();
                    ReaderToEntity(sdr, entity);
                    entityList.Add(entity);
                }
            }
            
            ResultCount = Convert.ToInt32(SiteBLL.GetEmailListValue("Count(id)", Where));

            return entityList;
        }
        /// <summary>
        /// 获取EmailList信息
        /// </summary>
        /// <param name="ad_id"></param>
        /// <returns></returns>
        public static EmailListInfo GetEmailListInfo(int id)
        {
            return GetEmailListInfo("id="+id);
        }
        /// <summary>
        /// 获取EmailList信息
        /// </summary>
        /// <param name="filter"></param>
        /// <returns></returns>
        public static EmailListInfo GetEmailListInfo(string filter)
        {
            EmailListInfo entity = new EmailListInfo();;

            using (IDataReader sdr = DatabaseProvider.GetInstance().GetEmailListInfo(filter))
            {
                if (sdr.Read())
                {
                    ReaderToEntity(sdr, entity);
                }
                else
                {
                    entity = null;
                }
                sdr.Close();
            }

            return entity;
        }
        /// <summary>
        /// 更新EmailList信息
        /// </summary>
        /// <param name="deliveryinfo"></param>
        public static void UpdateEmailListInfo(EmailListInfo entity)
        {
            DatabaseProvider.GetInstance().UpdateEmailListInfo(entity);
        }
        /// <summary>
        /// 添加EmailList信息
        /// </summary>
        /// <param name="deliveryinfo"></param>
        public static int InsertEmailListInfo(EmailListInfo entity)
        {
            return DatabaseProvider.GetInstance().InsertEmailListInfo(entity);
        }
        /// <summary>
        /// 更新EmailList指定字段的值
        /// </summary>
        /// <param name="fieldName"></param>
        /// <param name="ad_id"></param>
        public static void UpdateEmailListFieldValue(string fieldName, object fieldValue, int id)
        {
            DatabaseProvider.GetInstance().UpdateFieldValue("email_list", fieldName, fieldValue, "id", id);
        }
        /// <summary>
        /// 更新EmailList指定字段的值
        /// </summary>
        /// <param name="fieldName"></param>
        /// <param name="ad_ids"></param>
        public static void UpdateEmailListFieldValue(string fieldName, object fieldValue, string ids)
        {
            DatabaseProvider.GetInstance().UpdateFieldValue("email_list", fieldName, fieldValue, "id", ids);
        }
        /// <summary>
        /// 删除指定EmailList数据
        /// </summary>
        /// <param name="id"></param>
        public static void DeleteEmailListInfo(int id)
        {
            DatabaseProvider.GetInstance().DeleteEmailListInfo(id);
        }
        /// <summary>
        /// 按自定义条件删除EmailList中的数据
        /// </summary>
        /// <param name="tbname"></param>
        /// <param name="filter"></param>
        public static void DeleteEmailListInfo(string filter)
        {
            DatabaseProvider.GetInstance().DeleteData("email_list", filter);
        }
        /// <summary>
        /// 判断是否存在
        /// </summary>
        /// <param name="filter">查询条件</param>
        /// <returns></returns>
        public static bool ExistsEmailList(string filter)
        {
            return DatabaseProvider.GetInstance().ExistsEmailList(filter);
        }
        /// <summary>
        /// 获取EmailList单个值
        /// </summary>
        /// <param name="Fields">要获取的字段或函数，如Count(字段名)</param>
        /// <param name="filter"></param>
        /// <returns></returns>
        public static object GetEmailListValue(string Fields, string filter)
        {
            return DatabaseProvider.GetInstance().GetEmailListValue(Fields, filter);
        }
        /// <summary>
        /// 获取EmailList单个值
        /// </summary>
        /// <param name="Fields">要获取的字段或函数，如Count(字段名)</param>
        /// <param name="filter"></param>
        /// <returns></returns>
        public static object GetEmailListValue(string Fields)
        {
            return GetEmailListValue(Fields, "");
        }
    }
}