//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Data.Common;
using System.Reflection;

using DY.Common;
using DY.Cache;
using DY.Data;
using DY.Entity;

namespace DY.Site
{
    public partial class SiteBLL
    {
        /// <summary>
        /// 根据条件查询表中所有数据
        /// </summary>
        /// <param name="FieldOrder">以逗号分隔的排序字段列表,可以指定在字段后面指定DESC/ASC用于指定排序顺序</param>
        /// <param name="Where">查询条件</param>
        /// <returns></returns>
        public static ArrayList GetFeedbackAllList(string FieldOrder, string Where)
        {
            return GetFeedbackAllList(FieldOrder,"*", Where);
        }
        /// <summary>
        /// 根据条件查询表中所有数据
        /// </summary>
        /// <param name="FieldOrder">以逗号分隔的排序字段列表,可以指定在字段后面指定DESC/ASC用于指定排序顺序</param>
        /// <param name="strFields">要查询的字段列表</param>
        /// <param name="Where">查询条件</param>
        /// <returns></returns>
        public static ArrayList GetFeedbackAllList(string FieldOrder,string strFields, string Where)
        {
            ArrayList entityList = new ArrayList();
            using (IDataReader sdr = DatabaseProvider.GetInstance().GetAllData("feedback", strFields, FieldOrder, Where))
            {
                while (sdr.Read())
                {
                    FeedbackInfo entity = new FeedbackInfo();
                    ReaderToEntity(sdr, entity);
                    entityList.Add(entity);
                }
            }

            return entityList;
        }
        /// <summary>
        /// 获取Feedback分页列表数据
        /// </summary>
        /// <param name="PageCurrent">要显示的页码</param>
        /// <param name="PageSize">每页的大小(记录数)</param>
        /// <param name="Where">查询条件</param>
        /// <param name="ResultCount">总页数</param>
        /// <returns></returns>
        public static ArrayList GetFeedbackList(int PageCurrent, int PageSize, string FieldOrder, string Where, out int ResultCount)
        {
            return GetFeedbackList(PageCurrent, PageSize, "*", FieldOrder, Where, out ResultCount);
        }
        /// <summary>
        /// 获取Feedback分页列表数据
        /// </summary>
        /// <param name="PageCurrent">要显示的页码</param>
        /// <param name="PageSize">每页的大小(记录数)</param>
        /// <param name="Where">查询条件</param>
        /// <param name="ResultCount">总页数</param>
        /// <returns></returns>
        public static ArrayList GetFeedbackList(int PageCurrent, int PageSize, string strFields, string FieldOrder, string Where, out int ResultCount)
        {
            ArrayList entityList = new ArrayList();
            using (IDataReader sdr = DatabaseProvider.GetInstance().GetPagerData("feedback", "msg_id", PageCurrent, PageSize, strFields, FieldOrder, Where, out ResultCount))
            {
                while (sdr.Read())
                {
                    FeedbackInfo entity = new FeedbackInfo();
                    ReaderToEntity(sdr, entity);
                    entityList.Add(entity);
                }
            }
            
            ResultCount = Convert.ToInt32(SiteBLL.GetFeedbackValue("Count(msg_id)", Where));

            return entityList;
        }
        /// <summary>
        /// 获取Feedback信息
        /// </summary>
        /// <param name="ad_id"></param>
        /// <returns></returns>
        public static FeedbackInfo GetFeedbackInfo(int msg_id)
        {
            return GetFeedbackInfo("msg_id="+msg_id);
        }
        /// <summary>
        /// 获取Feedback信息
        /// </summary>
        /// <param name="filter"></param>
        /// <returns></returns>
        public static FeedbackInfo GetFeedbackInfo(string filter)
        {
            FeedbackInfo entity = new FeedbackInfo();;

            using (IDataReader sdr = DatabaseProvider.GetInstance().GetFeedbackInfo(filter))
            {
                if (sdr.Read())
                {
                    ReaderToEntity(sdr, entity);
                }
                else
                {
                    entity = null;
                }
                sdr.Close();
            }

            return entity;
        }
        /// <summary>
        /// 更新Feedback信息
        /// </summary>
        /// <param name="deliveryinfo"></param>
        public static void UpdateFeedbackInfo(FeedbackInfo entity)
        {
            DatabaseProvider.GetInstance().UpdateFeedbackInfo(entity);
        }
        /// <summary>
        /// 添加Feedback信息
        /// </summary>
        /// <param name="deliveryinfo"></param>
        public static int InsertFeedbackInfo(FeedbackInfo entity)
        {
            return DatabaseProvider.GetInstance().InsertFeedbackInfo(entity);
        }
        /// <summary>
        /// 更新Feedback指定字段的值
        /// </summary>
        /// <param name="fieldName"></param>
        /// <param name="ad_id"></param>
        public static void UpdateFeedbackFieldValue(string fieldName, object fieldValue, int msg_id)
        {
            DatabaseProvider.GetInstance().UpdateFieldValue("feedback", fieldName, fieldValue, "msg_id", msg_id);
        }
        /// <summary>
        /// 更新Feedback指定字段的值
        /// </summary>
        /// <param name="fieldName"></param>
        /// <param name="ad_ids"></param>
        public static void UpdateFeedbackFieldValue(string fieldName, object fieldValue, string msg_ids)
        {
            DatabaseProvider.GetInstance().UpdateFieldValue("feedback", fieldName, fieldValue, "msg_id", msg_ids);
        }
        /// <summary>
        /// 删除指定Feedback数据
        /// </summary>
        /// <param name="id"></param>
        public static void DeleteFeedbackInfo(int msg_id)
        {
            DatabaseProvider.GetInstance().DeleteFeedbackInfo(msg_id);
        }
        /// <summary>
        /// 按自定义条件删除Feedback中的数据
        /// </summary>
        /// <param name="tbname"></param>
        /// <param name="filter"></param>
        public static void DeleteFeedbackInfo(string filter)
        {
            DatabaseProvider.GetInstance().DeleteData("feedback", filter);
        }
        /// <summary>
        /// 判断是否存在
        /// </summary>
        /// <param name="filter">查询条件</param>
        /// <returns></returns>
        public static bool ExistsFeedback(string filter)
        {
            return DatabaseProvider.GetInstance().ExistsFeedback(filter);
        }
        /// <summary>
        /// 获取Feedback单个值
        /// </summary>
        /// <param name="Fields">要获取的字段或函数，如Count(字段名)</param>
        /// <param name="filter"></param>
        /// <returns></returns>
        public static object GetFeedbackValue(string Fields, string filter)
        {
            return DatabaseProvider.GetInstance().GetFeedbackValue(Fields, filter);
        }
        /// <summary>
        /// 获取Feedback单个值
        /// </summary>
        /// <param name="Fields">要获取的字段或函数，如Count(字段名)</param>
        /// <param name="filter"></param>
        /// <returns></returns>
        public static object GetFeedbackValue(string Fields)
        {
            return GetFeedbackValue(Fields, "");
        }
    }
}