//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Data.Common;
using System.Reflection;

using DY.Common;
using DY.Cache;
using DY.Data;
using DY.Entity;

namespace DY.Site
{
    public partial class SiteBLL
    {
        /// <summary>
        /// 根据条件查询表中所有数据
        /// </summary>
        /// <param name="FieldOrder">以逗号分隔的排序字段列表,可以指定在字段后面指定DESC/ASC用于指定排序顺序</param>
        /// <param name="Where">查询条件</param>
        /// <returns></returns>
        public static ArrayList GetVoteOptionAllList(string FieldOrder, string Where)
        {
            return GetVoteOptionAllList(FieldOrder,"*", Where);
        }
        /// <summary>
        /// 根据条件查询表中所有数据
        /// </summary>
        /// <param name="FieldOrder">以逗号分隔的排序字段列表,可以指定在字段后面指定DESC/ASC用于指定排序顺序</param>
        /// <param name="strFields">要查询的字段列表</param>
        /// <param name="Where">查询条件</param>
        /// <returns></returns>
        public static ArrayList GetVoteOptionAllList(string FieldOrder,string strFields, string Where)
        {
            ArrayList entityList = new ArrayList();
            using (IDataReader sdr = DatabaseProvider.GetInstance().GetAllData("vote_option", strFields, FieldOrder, Where))
            {
                while (sdr.Read())
                {
                    VoteOptionInfo entity = new VoteOptionInfo();
                    ReaderToEntity(sdr, entity);
                    entityList.Add(entity);
                }
            }

            return entityList;
        }
        /// <summary>
        /// 获取VoteOption分页列表数据
        /// </summary>
        /// <param name="PageCurrent">要显示的页码</param>
        /// <param name="PageSize">每页的大小(记录数)</param>
        /// <param name="Where">查询条件</param>
        /// <param name="ResultCount">总页数</param>
        /// <returns></returns>
        public static ArrayList GetVoteOptionList(int PageCurrent, int PageSize, string FieldOrder, string Where, out int ResultCount)
        {
            return GetVoteOptionList(PageCurrent, PageSize, "*", FieldOrder, Where, out ResultCount);
        }
        /// <summary>
        /// 获取VoteOption分页列表数据
        /// </summary>
        /// <param name="PageCurrent">要显示的页码</param>
        /// <param name="PageSize">每页的大小(记录数)</param>
        /// <param name="Where">查询条件</param>
        /// <param name="ResultCount">总页数</param>
        /// <returns></returns>
        public static ArrayList GetVoteOptionList(int PageCurrent, int PageSize, string strFields, string FieldOrder, string Where, out int ResultCount)
        {
            ArrayList entityList = new ArrayList();
            using (IDataReader sdr = DatabaseProvider.GetInstance().GetPagerData("vote_option", "option_id", PageCurrent, PageSize, strFields, FieldOrder, Where, out ResultCount))
            {
                while (sdr.Read())
                {
                    VoteOptionInfo entity = new VoteOptionInfo();
                    ReaderToEntity(sdr, entity);
                    entityList.Add(entity);
                }
            }
            
            ResultCount = Convert.ToInt32(SiteBLL.GetVoteOptionValue("Count(option_id)", Where));

            return entityList;
        }
        /// <summary>
        /// 获取VoteOption信息
        /// </summary>
        /// <param name="ad_id"></param>
        /// <returns></returns>
        public static VoteOptionInfo GetVoteOptionInfo(int option_id)
        {
            return GetVoteOptionInfo("option_id="+option_id);
        }
        /// <summary>
        /// 获取VoteOption信息
        /// </summary>
        /// <param name="filter"></param>
        /// <returns></returns>
        public static VoteOptionInfo GetVoteOptionInfo(string filter)
        {
            VoteOptionInfo entity = new VoteOptionInfo();;

            using (IDataReader sdr = DatabaseProvider.GetInstance().GetVoteOptionInfo(filter))
            {
                if (sdr.Read())
                {
                    ReaderToEntity(sdr, entity);
                }
                else
                {
                    entity = null;
                }
                sdr.Close();
            }

            return entity;
        }
        /// <summary>
        /// 更新VoteOption信息
        /// </summary>
        /// <param name="deliveryinfo"></param>
        public static void UpdateVoteOptionInfo(VoteOptionInfo entity)
        {
            DatabaseProvider.GetInstance().UpdateVoteOptionInfo(entity);
        }
        /// <summary>
        /// 添加VoteOption信息
        /// </summary>
        /// <param name="deliveryinfo"></param>
        public static int InsertVoteOptionInfo(VoteOptionInfo entity)
        {
            return DatabaseProvider.GetInstance().InsertVoteOptionInfo(entity);
        }
        /// <summary>
        /// 更新VoteOption指定字段的值
        /// </summary>
        /// <param name="fieldName"></param>
        /// <param name="ad_id"></param>
        public static void UpdateVoteOptionFieldValue(string fieldName, object fieldValue, int option_id)
        {
            DatabaseProvider.GetInstance().UpdateFieldValue("vote_option", fieldName, fieldValue, "option_id", option_id);
        }
        /// <summary>
        /// 更新VoteOption指定字段的值
        /// </summary>
        /// <param name="fieldName"></param>
        /// <param name="ad_ids"></param>
        public static void UpdateVoteOptionFieldValue(string fieldName, object fieldValue, string option_ids)
        {
            DatabaseProvider.GetInstance().UpdateFieldValue("vote_option", fieldName, fieldValue, "option_id", option_ids);
        }
        /// <summary>
        /// 删除指定VoteOption数据
        /// </summary>
        /// <param name="id"></param>
        public static void DeleteVoteOptionInfo(int option_id)
        {
            DatabaseProvider.GetInstance().DeleteVoteOptionInfo(option_id);
        }
        /// <summary>
        /// 按自定义条件删除VoteOption中的数据
        /// </summary>
        /// <param name="tbname"></param>
        /// <param name="filter"></param>
        public static void DeleteVoteOptionInfo(string filter)
        {
            DatabaseProvider.GetInstance().DeleteData("vote_option", filter);
        }
        /// <summary>
        /// 判断是否存在
        /// </summary>
        /// <param name="filter">查询条件</param>
        /// <returns></returns>
        public static bool ExistsVoteOption(string filter)
        {
            return DatabaseProvider.GetInstance().ExistsVoteOption(filter);
        }
        /// <summary>
        /// 获取VoteOption单个值
        /// </summary>
        /// <param name="Fields">要获取的字段或函数，如Count(字段名)</param>
        /// <param name="filter"></param>
        /// <returns></returns>
        public static object GetVoteOptionValue(string Fields, string filter)
        {
            return DatabaseProvider.GetInstance().GetVoteOptionValue(Fields, filter);
        }
        /// <summary>
        /// 获取VoteOption单个值
        /// </summary>
        /// <param name="Fields">要获取的字段或函数，如Count(字段名)</param>
        /// <param name="filter"></param>
        /// <returns></returns>
        public static object GetVoteOptionValue(string Fields)
        {
            return GetVoteOptionValue(Fields, "");
        }
    }
}