//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using System.Data;
using System.Data.Common;

using CShop.Entity;

namespace CShop.Data
{
    /// <summary>
    /// 系统接口类
    /// </summary>
    public partial interface IDataProvider
    {
        /// <summary>
        /// 插入InternalLinks
        /// </summary>
        /// <param name="adinfo"></param>
        int InsertInternalLinksInfo(InternalLinksInfo entity);
        /// <summary>
        /// 更新InternalLinks
        /// </summary>
        /// <param name="adinfo"></param>
        void UpdateInternalLinksInfo(InternalLinksInfo entity);
        /// <summary>
        /// 获取单个InternalLinks
        /// </summary>
        /// <param name="ad_id"></param>
        /// <returns></returns>
        DbDataReader GetInternalLinksInfo(int ID);
        /// <summary>
        /// 获取单个InternalLinks
        /// </summary>
        /// <param name="filter">查询条件</param>
        /// <returns></returns>
        DbDataReader GetInternalLinksInfo(string filter);
        /// <summary>
        /// 删除InternalLinks（按主键删除）
        /// </summary>
        /// <param name="ad_id"></param>
        /// <returns></returns>
        void DeleteInternalLinksInfo(int ID);
        /// <summary>
        /// 判断是否存在
        /// </summary>
        /// <param name="filter">查询条件</param>
        /// <returns></returns>
        bool ExistsInternalLinks(string filter);
        /// <summary>
        /// 获取InternalLinks单个值
        /// </summary>
        /// <param name="Fields">要获取的字段或函数，如Count(字段名)</param>
        /// <param name="filter"></param>
        /// <returns></returns>
        object GetInternalLinksValue(string Fields, string filter);
    }
}
