//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DY.LanguagePack {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DY.LanguagePack.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 next 的本地化字符串。
        /// </summary>
        public static string page_class_end {
            get {
                return ResourceManager.GetString("page_class_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 prev 的本地化字符串。
        /// </summary>
        public static string page_class_frist {
            get {
                return ResourceManager.GetString("page_class_frist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 prev 的本地化字符串。
        /// </summary>
        public static string page_class_index {
            get {
                return ResourceManager.GetString("page_class_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 next 的本地化字符串。
        /// </summary>
        public static string page_class_next {
            get {
                return ResourceManager.GetString("page_class_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 num 的本地化字符串。
        /// </summary>
        public static string page_class_shu {
            get {
                return ResourceManager.GetString("page_class_shu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 on 的本地化字符串。
        /// </summary>
        public static string page_class_yes {
            get {
                return ResourceManager.GetString("page_class_yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每页 的本地化字符串。
        /// </summary>
        public static string page_eachPage {
            get {
                return ResourceManager.GetString("page_eachPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尾页 的本地化字符串。
        /// </summary>
        public static string page_end {
            get {
                return ResourceManager.GetString("page_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string page_index {
            get {
                return ResourceManager.GetString("page_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条记录 的本地化字符串。
        /// </summary>
        public static string page_information {
            get {
                return ResourceManager.GetString("page_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        public static string page_next {
            get {
                return ResourceManager.GetString("page_next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        public static string page_onPage {
            get {
                return ResourceManager.GetString("page_onPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共 的本地化字符串。
        /// </summary>
        public static string page_total {
            get {
                return ResourceManager.GetString("page_total", resourceCulture);
            }
        }
    }
}
